apiVersion: v2
name: vpnbuilder
description: Developer-First Distributed VPN Control Plane and Node Agent
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - vpn
  - wireguard
  - xray
  - vless
  - proxy
home: https://github.com/ivanchik-byte/Simple-VPN-Builder
sources:
  - https://github.com/ivanchik-byte/Simple-VPN-Builder
maintainers:
  - name: Simple-VPN-Builder Maintainers
    url: https://github.com/ivanchik-byte/Simple-VPN-Builder
