root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/vpnbuilder-agent ./cmd/agent"
bin = "./tmp/vpnbuilder-agent"
include_ext = ["go", "yaml", "yml"]
exclude_dir = ["assets", "tmp", "vendor", "bin", "docker"]
include_dir = ["cmd/agent", "internal/agent", "internal/shared", "pkg"]
delay = 1000
stop_on_error = true
log = "air-agent.log"

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true