run:
  timeout: 5m
  tests: true
  go: '1.24'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - revive

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: true
      - name: blank-imports
        disabled: true

issues:
  exclude-dirs:
    - pkg/proto
    - internal/controlplane/store