import { createContext, useContext, useState, type ReactNode } from 'react';

export type Lang = 'en' | 'ru';

const en = {
  'app.brand': 'Control Plane',
  'app.version': '0.1.0v',
  'nav.dashboard': 'Dashboard',
  'nav.users': 'Users & Subscriptions',
  'nav.nodes': 'Exit Nodes',
  'nav.plans': 'Plans & Pricing',
  'nav.credentials': 'Access Keys',
  'nav.analytics': 'Traffic & Logs',
  'nav.broadcast': 'Broadcasts',
  'nav.audit': 'Audit Log',
  'nav.settings': 'Settings & Gateways',
  'nav.copilot': 'Infra Copilot',
  'nav.copilot.sub': 'AI Agent Online',
  'nav.official': 'Official Channel',
  'nav.preview': 'dashboard-v2 preview',
  'nav.classic': 'classic UI at /admin',
  'nav.logout': 'Sign Out',
  'dash.title': 'Cluster Overview',
  'dash.subtitle': 'Real-time telemetry and fleet metrics',
  'dash.paused': 'paused in background',
  'dash.active': 'CLUSTER HEALTHY',
  'dash.cluster': 'CLUSTER',
  'dash.unreachable': 'telemetry offline',
  'dash.connecting': 'connecting...',
  'dash.retry': 'Telemetry endpoint is unreachable. Check control plane connection, then retry.',
  'dash.cpu': 'CPU Load',
  'dash.cpu.sub': 'Load Avg',
  'dash.cpu.host': 'host cpu',
  'dash.mem': 'Memory',
  'dash.disk': 'Disk Storage',
  'dash.net': 'Network I/O',
  'dash.h.cpu': 'CPU load history',
  'dash.h.mem': 'Memory usage history',
  'dash.h.disk': 'Disk usage history',
  'dash.h.net': 'Network throughput history',
  'dash.collapse': 'Collapse',
  'dash.nodes': 'Active Nodes',
  'dash.nodes.sub': 'servers online',
  'dash.users': 'Active Users',
  'dash.users.registered': 'registered users',
  'dash.protoCount': 'Protocols',
  'dash.protoCount.sub': 'WG • AWG • VLESS',
  'dash.traffic': 'Total Traffic (30d)',
  'dash.traffic.sub': 'Aggregated bandwidth',
  'dash.creds': 'Issued Keys',
  'dash.creds.sub': 'across all protocols',
  'dash.throughput': 'Current Throughput',
  'dash.in': 'inbound',
  'dash.out': 'outbound',
  'dash.proto': 'Protocol Distribution',
  'dash.proto.sub': 'share of issued client keys',
  'dash.proto.empty': 'No credentials yet',
  'dash.proto.emptyHint': 'Issue your first key to see protocol distribution',
  'dash.top': 'Top Consumers',
  'dash.top.sub': 'users with highest traffic consumption',
  'dash.allUsers': 'All users →',
  'dash.top.empty': 'No traffic recorded yet',
  'dash.top.emptyHint': 'Usage stats will appear after the first client sessions',
  'dash.fleet': 'Exit Node Fleet',
  'dash.fleet.sub': 'Live node telemetry and connection status',
  'dash.manage': 'Manage Nodes',
  'dash.col.node': 'Node / Location',
  'dash.col.status': 'Status',
  'dash.col.host': 'Host : Port',
  'dash.col.proto': 'Protocols',
  'dash.col.seen': 'Last Seen',
  'dash.col.actions': 'Actions',
  'dash.inspect': 'Inspect →',
  'dash.fleet.empty': 'No exit nodes registered yet. Launch an agent or add a node manually.',
  'dash.global': 'Global',
  'dash.unknown': 'unknown',
  'dash.never': 'Never',
  'dash.themeToggle': 'Toggle color theme',
  'dash.samplesLive': 'last 40 samples · live',
  'dash.chartMax': 'max',
  'dash.chartNow': 'now',
  'nodes.title': 'Exit Nodes',
  'nodes.subtitle': 'Cluster nodes and fleet operations',
  'nodes.total': 'Total nodes:',
  'nodes.register': '+ Add Node',
  'nodes.col.name': 'Name',
  'nodes.col.status': 'Status',
  'nodes.col.endpoint': 'VPN Endpoint',
  'nodes.col.pubkey': 'Public Key',
  'nodes.col.grpc': 'Control Plane (gRPC)',
  'nodes.col.heartbeat': 'Heartbeat',
  'nodes.col.actions': 'Actions',
  'nodes.inspect': 'Inspect',
  'nodes.delete': 'Delete',
  'nodes.confirmTitle': 'Delete Exit Node',
  'nodes.deleteConfirm': 'Delete node "{name}"? Active connections on this node will be disconnected.',
  'nodes.err.load': 'Failed to load nodes',
  'nodes.err.register': 'Failed to register node',
  'nodes.err.delete': 'Failed to delete node',
  'nodes.empty': 'No exit nodes found.',
  'nodes.modal.title': 'Register Exit Node',
  'nodes.modal.name': 'Node Name',
  'nodes.modal.namePh': 'e.g. de-frankfurt-01',
  'nodes.modal.region': 'Region / Country',
  'nodes.modal.regionPh': 'e.g. EU-DE',
  'nodes.modal.host': 'Public IP / Host',
  'nodes.modal.hostPh': 'e.g. 217.26.25.6',
  'nodes.modal.port': 'Port',
  'nodes.modal.pubkey': 'WireGuard Public Key',
  'nodes.modal.pubkeyPh': 'Base64 public key',
  'nodes.modal.cancel': 'Cancel',
  'nodes.modal.save': 'Save Node',
  'users.title': 'Users & Subscriptions',
  'users.subtitle': 'User quotas, plans and universal client subscriptions',
  'users.seg.all': 'All Users',
  'users.seg.active': 'Active Subscriptions',
  'users.seg.lead': 'Bot Leads',
  'users.seg.trial': 'Free Trials',
  'users.seg.expired': 'Expired',
  'users.seg.banned': 'Banned',
  'users.create': '+ New User',
  'users.col.user': 'User / Contact',
  'users.col.life': 'Status',
  'users.col.quota': 'Traffic Quota',
  'users.col.token': 'Subscription Token',
  'users.col.exp': 'Expiration',
  'users.col.actions': 'Actions',
  'users.noEmail': 'no email',
  'users.editEmail': '[Edit Email]',
  'users.seen': 'Seen',
  'users.unlimited': 'Unlimited',
  'users.permanent': 'Permanent',
  'users.plan': 'Plan',
  'users.lead': 'Bot Lead',
  'users.custom': 'Custom',
  'users.message': 'Message',
  'users.assign': 'Assign Plan',
  'users.reset': 'Reset Traffic',
  'users.ban': 'Ban',
  'users.unban': 'Unban',
  'users.delete': 'Delete',
  'users.empty': 'No users found in this category.',
  'users.delTitle': 'Delete User',
  'users.deleteConfirm': 'Permanently delete user "{name}"? All associated VPN keys will be revoked.',
  'users.err.load': 'Failed to load users',
  'users.err.action': 'Operation failed',
  'users.tip.id': 'Internal ID',
  'users.tip.openTg': 'Open in Telegram',
  'users.tip.viewSub': 'Subscription links & QR code',
  'users.tip.resetQuota': 'Reset consumed traffic quota',
  'users.tip.ban': 'Ban user account',
  'users.tip.unban': 'Unban user account',
  'users.tip.message': 'Send personal Telegram message',
  'users.tip.assign': 'Assign or gift plan',
  'users.trialDuration': 'FREE TRIAL ({hours}h)',
  'users.st.active': 'Active',
  'users.st.lead': 'Lead',
  'users.st.trial': 'Trial',
  'users.st.expired': 'Expired',
  'users.st.banned': 'Banned',
  'users.qr.title': 'Universal Subscription',
  'users.qr.user': 'User: ',
  'users.qr.scan': 'Scan with Sing-box, V2Ray, Happ, Hiddify or Amnezia',
  'users.qr.url': 'Universal Subscription URL',
  'users.qr.copy': 'Copy URL',
  'users.qr.copied': 'URL copied to clipboard!',
  'users.qr.raw': 'Open Config ↗',
  'users.c.title': 'Create User Subscription',
  'users.c.sub': 'Provision VPN access keys and subscription profile',
  'users.c.username': 'Username',
  'users.c.usernamePh': 'e.g. alex_smith',
  'users.c.email': 'Email (optional)',
  'users.c.tgId': 'Telegram User ID (optional)',
  'users.c.tgIdHint': 'Numeric TG ID to link with Telegram bot',
  'users.c.tgUser': 'Telegram @username (optional)',
  'users.c.tgUserHint': 'Without the @ prefix',
  'users.c.mode': 'Plan Mode',
  'users.c.preset': 'Preset Catalog Plan',
  'users.c.custom': 'Custom / Exclusive Tier',
  'users.c.plan': 'Select Plan',
  'users.c.noPlans': 'No catalog plans available. Switch to Custom mode.',
  'users.c.duration': 'Duration (Days)',
  'users.c.durationHint': 'Subscription duration before renewal is required',
  'users.c.limit': 'Traffic Limit (GB)',
  'users.c.unlimited': 'Unlimited Traffic',
  'users.c.validity': 'Validity (Days)',
  'users.c.never': 'Never Expires',
  'users.c.note': 'Note (optional)',
  'users.c.notePh': 'e.g. VIP client, partner account',
  'users.c.cancel': 'Cancel',
  'users.c.create': 'Create Subscription',
  'users.dm.title': 'Send Direct Telegram Message',
  'users.dm.sub': 'Send personal notification to user via bot',
  'users.dm.text': 'Message Text (HTML supported)',
  'users.dm.send': 'Send Message',
  'users.assign.title': 'Assign / Gift Subscription Plan',
  'users.assign.sub': 'Set service plan and bandwidth quota',
  'users.assign.plan': 'Select Service Plan',
  'users.assign.duration': 'Duration (Days)',
  'users.assign.durationHint': 'Calculates expiration timestamp starting from today.',
  'users.assign.notify': "Send renewal confirmation to user's Telegram",
  'users.assign.go': 'Apply Plan',
  'users.email.title': 'Link / Update Subscriber Email',
  'users.email.sub': 'Email address used for account recovery',
  'users.email.label': 'Email Address',
  'users.email.save': 'Save Email',  'plans.title': 'Plans & Pricing',
  'plans.subtitle': 'Bandwidth limits, pricing periods and protocol entitlements',
  'plans.count': 'Total tiers:',
  'plans.new': '+ New Plan',
  'plans.trial': 'FREE TRIAL',
  'plans.bandwidth': 'Bandwidth:',
  'plans.unlimited': 'Unlimited',
  'plans.devices': 'Simultaneous Devices:',
  'plans.devicesUnit': 'devices',
  'plans.trialDur': 'Trial Duration:',
  'plans.hours': 'hours',
  'plans.durations': 'Pricing by Duration:',
  'plans.edit': 'Edit',
  'plans.remove': 'Delete',
  'plans.readonly': 'System Plan',
  'plans.empty': 'No service plans configured yet. Create a plan to associate quotas with users.',
  'plans.delTitle': 'Delete Plan',
  'plans.deleteConfirm': 'Delete plan "{name}"? Existing subscribers on this plan will remain active.',
  'plans.err.load': 'Failed to load plans',
  'plans.err.delete': 'Failed to delete plan',
  'plans.perMonth': '/mo',
  'plans.dynamic': 'Auto',
  'plans.d1': '1 mo:',
  'plans.d3': '3 mo:',
  'plans.d6': '6 mo:',
  'plans.d12': '12 mo:',
  'plans.c.title': 'Plan Builder: Create Tier',
  'plans.c.sub': 'Configure protocols, device limits, quotas and pricing by period',
  'plans.c.name': 'Plan Name',
  'plans.c.protos': 'Allowed Protocols',
  'plans.c.limit': 'Traffic Limit (GB)',
  'plans.c.limitHint': 'Enter 0 for unlimited bandwidth',
  'plans.c.devices': 'Max Concurrent Devices',
  'plans.c.devicesHint': 'Maximum concurrent connected keys/devices',
  'plans.c.trial': 'Set as Free Trial Tier',
  'plans.c.trialHours': 'Trial Duration (Hours)',
  'plans.c.trialHint': 'New Telegram bot users will receive this quota and duration automatically upon first start.',
  'plans.c.pricing': 'Pricing by Duration (USD)',
  'plans.c.p1': '1 Month Price',
  'plans.c.p3': '3 Months Price',
  'plans.c.p6': '6 Months Price',
  'plans.c.p12': '12 Months Price',
  'plans.c.auto': 'Leave blank for automatic discount',
  'plans.c.stars': 'Price in Telegram Stars',
  'plans.c.free': '100% Free Tier: USD and Telegram Stars pricing is disabled for trial subscriptions.',
  'plans.c.cancel': 'Cancel',
  'plans.c.save': 'Save Plan',
  'plans.e.title': 'Plan Builder: Edit Plan',
  'plans.e.updating': 'Editing ',
  'plans.e.update': 'Update Plan',
  'creds.title': 'Access Keys',
  'creds.subtitle': 'Client keypairs, credentials and network tunnels',
  'creds.total': 'Total keys:',
  'creds.col.user': 'User',
  'creds.col.proto': 'Protocol',
  'creds.col.ipv4': 'Tunnel IPv4',
  'creds.col.key': 'Public Key / UUID',
  'creds.col.status': 'Status',
  'creds.col.actions': 'Actions',
  'creds.vless': 'VLESS Client',
  'creds.uuid': 'UUID / Flow assigned',
  'creds.rotate': 'Rotate Key',
  'creds.rotateTitle': 'Re-issue cryptographic keypair for this client',
  'creds.revoke': 'Revoke',
  'creds.delTitle': 'Revoke Access Key',
  'creds.deleteConfirm': 'Permanently revoke this access key? Client connection will terminate immediately.',
  'creds.err.load': 'Failed to load credentials',
  'creds.err.action': 'Operation failed',
  'creds.empty': 'No access keys generated yet.',
  'analytics.title': 'Traffic Analytics & Audit Log',
  'analytics.subtitle': 'Time-series bandwidth monitoring and administrative action audit',
  'analytics.rx': 'Inbound Traffic (RX)',
  'analytics.rx.sub': 'Aggregated internet download volume',
  'analytics.tx': 'Outbound Traffic (TX)',
  'analytics.tx.sub': 'Aggregated delivery volume to clients',
  'analytics.total': 'Total Traffic Volume',
  'analytics.total.sub': 'Total network throughput',
  'analytics.trail': 'System Action Audit Trail',
  'analytics.trail.sub': 'Recorded administrative mutations and security events',
  'analytics.full': 'Open Full Audit Log →',
  'analytics.col.time': 'Timestamp',
  'analytics.col.action': 'Action',
  'analytics.col.resource': 'Resource',
  'analytics.col.details': 'Details / Diff',
  'analytics.col.ip': 'IP Address',
  'analytics.col.inspect': 'Inspect',
  'analytics.empty': 'No audit records logged yet.',
  'analytics.modal': 'Audit Record Details',
  'analytics.payload': 'PAYLOAD',
  'analytics.close': 'Close',
  'analytics.internal': 'Internal',
  'analytics.system': 'system',
  'analytics.alertBadge': 'SECURITY ALERT',
  'audit.title': 'Administrative Audit Log',
  'audit.subtitle': 'Configuration changes, permission updates and tamper-resistant event trail',
  'audit.filterAction': 'Filter by action (e.g. DirectMessageUser)...',
  'audit.filterResource': 'Filter by resource (e.g. user, admin)...',
  'audit.apply': 'Apply Filter',
  'audit.stored': 'records logged (tamper-resistant WORM storage)',
  'audit.retention': 'Configure retention policy & logging',
  'login.title': 'Control Plane',
  'login.subtitle': 'Cluster administrator sign-in',
  'login.user': 'Username or Email',
  'login.userPh': 'admin@example.com',
  'login.pass': 'Password',
  'login.totp': '2FA TOTP Code',
  'login.totpHint': '(if enabled)',
  'login.go': 'Sign In',
  'login.failed': 'Authentication failed. Please check credentials and try again.',
  'nd.back': '← Back to Nodes',
  'nd.drain': 'Drain Traffic',
  'nd.online': 'Set Online',
  'nd.telemetry': 'Hardware Telemetry & Utilization',
  'nd.protos': 'Configured Protocols & Services',
  'nd.peers': 'Node Peers & Keys',
  'nd.col.user': 'User',
  'nd.col.proto': 'Protocol',
  'nd.col.ipv4': 'Assigned IPv4',
  'nd.col.key': 'Public Key / UUID',
  'nd.col.status': 'Status',
  'nd.empty': 'No peers assigned to this node yet.',
  'nd.grpc': 'gRPC:',
  'nd.offline': 'Agent Offline',
  'nd.offlineHint': 'Telemetry data will appear as soon as the node agent connects',
  'nd.proto.wgDesc': 'Interface: wg0',
  'nd.proto.awgDesc': 'Junk packet & header scrambling active',
  'nd.proto.vlessDesc': 'SNI: dl.google.com • Flow: xtls-rprx-vision',
  'bc.title': 'Broadcasts & Announcements',
  'bc.subtitle': 'Targeted Telegram announcements with rate limit protection',
  'bc.sent': 'Broadcast campaign has been queued and is dispatching in background (~25 msgs/sec).',
  'bc.compose': 'Compose Campaign',
  'bc.cTitle': 'Campaign Title',
  'bc.cTitlePh': 'e.g. Scheduled Infrastructure Maintenance',
  'bc.segment': 'Target Audience Segment',
  'bc.seg.all': 'All Users (Active, Trial, Leads & Expired)',
  'bc.seg.leads': 'Bot Leads (Launched bot without subscription)',
  'bc.seg.active': 'Active Subscribers Only',
  'bc.seg.expired': 'Expired / Inactive Accounts',
  'bc.body': 'Message Body (HTML / Markdown)',
  'bc.bodyPh': 'Type announcement message text...',
  'bc.btnBox': 'Optional Action Button',
  'bc.btnLabel': 'Button Label',
  'bc.btnLabelPh': 'e.g. Renew Subscription',
  'bc.btnUrl': 'Button URL',
  'bc.note': 'Dispatches asynchronously via Telegram Bot API with token-bucket rate limiting (~25 msgs/sec) to avoid 429 flood errors.',
  'bc.dispatch': 'Launch Broadcast',
  'bc.history': 'Campaign History',
  'bc.total': 'Total campaigns:',
  'bc.col.title': 'Title / Segment',
  'bc.col.status': 'Status',
  'bc.col.sent': 'Delivered / Total',
  'bc.col.failed': 'Failed',
  'bc.col.created': 'Created',
  'bc.segmentLbl': 'Segment:',
  'bc.empty': 'No broadcast campaigns recorded yet.',
  'bc.status.completed': 'COMPLETED',
  'bc.status.sending': 'SENDING',
  'bc.status.failed': 'FAILED',
  'bc.status.pending': 'PENDING',
  'bc.err.csrf': 'Security check failed (CSRF)',
  'bc.err.create': 'Failed to create broadcast campaign',
  'set.title': 'Settings & Administration',
  'set.subtitle': 'Administrators, payment gateways, integrations and developer keys',
  'set.billing': 'Billing & Payment Gateways',
  'set.billing.sub': 'Payment provider credentials, webhooks and currency rules',
  'set.replies': 'Bot Replies & Copy',
  'set.replies.sub': 'Customer onboarding flow, trial conversion and funnel texts',
  'set.referrals': 'Referral & Affiliate Program',
  'set.referrals.sub': 'Growth engine, bonus rules and anti-abuse safeguards',
  'set.security': 'Subscriber Email & Security Policy',
  'set.security.sub': 'Account protection, OTP verification and SMTP delivery settings',
  'set.partners': 'Partners, Mini Apps & White-Label',
  'set.partners.sub': 'Dedicated bots, channel subscription walls and Telegram Web Apps',
  'set.open': 'Open →',
  'set.tab.admins': 'Admins & Keys',
  'set.tab.billing': 'Billing',
  'set.tab.replies': 'Bot Replies',
  'set.tab.referrals': 'Referrals',
  'set.tab.security': 'Security',
  'set.tab.partners': 'Partners',
  'set.tab.ai': 'AI Copilot',
  'set.save': 'Save Changes',
  'set.saved': 'Settings saved successfully.',
  'set.failed': 'Failed to save settings.',
  'set.admins': 'System Administrators',
  'set.addAdmin': 'Add Administrator',
  'set.email': 'Email',
  'set.password': 'Password',
  'set.role': 'Role',
  'set.add': 'Add',
  'set.cancel': 'Cancel',
  'set.delete': 'Delete',
  'set.keys': 'Developer API Keys',
  'set.issueKey': 'Create API Key',
  'set.keyName': 'Key Description',
  'set.keyNamePh': 'e.g. Bot-Service-Key',
  'set.scope': 'Access Scope',
  'set.scope.admin': 'admin (Full control)',
  'set.scope.read': 'read (Telemetry & metrics only)',
  'set.scope.write': 'write (Node & User operations)',
  'set.generate': 'Generate Key',
  'set.copyToken': 'Copy Token',
  'set.totp': 'Two-Factor Authentication (2FA)',
  'set.totpSetup': 'Configure in classic console',
  'set.totpOn': 'Enabled',
  'set.totpOff': 'Disabled',
  'set.disable': 'Disable',
  'set.billing.title': 'Billing & Payment Gateways',
  'set.billing.crypto': 'CryptoBot API Token',
  'set.billing.cryptoOn': 'CryptoBot payments enabled',
  'set.billing.starsOn': 'Telegram Stars payments enabled',
  'set.billing.starsPrice': 'Monthly price in Stars',
  'set.billing.webhook': 'Webhook Secret Key',
  'set.billing.sales': 'Sales Bot Token',
  'set.billing.alert': 'Alert Bot Token',
  'set.billing.alertChat': 'Alert Chat ID',
  'set.billing.alertOn': 'Alerts enabled',
  'set.gateways': 'Connected Payment Gateways',
  'set.gw.name': 'Gateway Name',
  'set.gw.token': 'API Token',
  'set.gw.enable': 'Enabled',
  'set.gw.add': 'Add Gateway',
  'set.gw.toggle': 'Toggle',
  'set.gw.on': 'on',
  'set.gw.off': 'off',
  'set.replies.title': 'Telegram Bot Replies & Customer Journey',
  'set.replies.bot': 'Telegram Bot API Token & Branding',
  'set.replies.botToken': 'Bot Token',
  'set.replies.maskedHint': 'leave masked to keep current token',
  'set.replies.channel': 'Channel Link',
  'set.replies.support': 'Support Link',
  'set.replies.welcome': 'Welcome Message',
  'set.replies.templates': 'templates',
  'set.replies.mediaUrl': 'Image / GIF URL (optional)',
  'set.replies.mediaFile': '... or upload an image (max 15MB)',
  'set.replies.bannerTitle': 'Master Welcome Banner',
  'set.replies.bannerUrl': 'Banner image URL',
  'set.replies.bannerFile': '... or upload a banner (max 15MB)',
  'set.replies.placeholders': 'Placeholders — click to append to the last edited template:',
  'set.replies.preview': 'Live Telegram Preview',
  'set.replies.previewHint': 'Mock preview — placeholders filled with demo values',
  'set.ref.title': 'Referral & Growth Engine',
  'set.ref.on': 'Referral program enabled',
  'set.ref.model': 'Reward Model',
  'set.ref.inviter': 'Referrer Reward (Days)',
  'set.ref.invitee': 'Invited Friend Welcome (Days)',
  'set.ref.commission': 'Affiliate Revenue Share (%)',
  'set.ref.min': 'Minimum Purchase Amount',
  'set.ref.qual': 'Qualification Rule',
  'set.ref.cap': 'Daily Cap',
  'set.ref.expired': 'Reward accounts with expired subscriptions',
  'set.sec.title': 'Subscriber Email & Security Policy',
  'set.sec.policy': 'Subscriber Email Policy',
  'set.sec.policyLabel': 'Email Requirement (optional / required / disabled)',
  'set.sec.otp': 'Email OTP Verification',
  'set.sec.smtp': 'Mail Delivery Engine (SMTP / Simulated)',
  'set.sec.host': 'SMTP Host',
  'set.sec.port': 'SMTP Port',
  'set.sec.user': 'SMTP Username',
  'set.sec.pass': 'SMTP Password',
  'set.sec.from': 'SMTP From Email',
  'set.sec.sim': 'Simulated delivery (no real emails sent)',
  'set.retention': 'Audit Trail Retention Policy',
  'set.retention.sub': 'Recorded event categories and retention window.',
  'set.retention.days': 'Retention Days (0 = indefinite)',
  'set.partners.title': 'Partner Brands & White-Label',
  'set.partners.add': 'Add Partner Brand & Bot',
  'set.partners.name': 'Brand Name',
  'set.partners.slug': 'Slug Identifier',
  'set.partners.token': 'Bot Token',
  'set.partners.username': 'Bot Username',
  'set.partners.channel': 'Channel Link',
  'set.partners.support': 'Support Link',
  'set.partners.domain': 'Custom Domain',
  'set.partners.miniapp': 'Telegram Mini App URL',
  'set.partners.welcome': 'Welcome Message',
  'set.partners.require': 'Require Channel Subscription',
  'set.partners.empty': 'No partner brands configured yet.',
  'set.admin.deleteConfirm': 'Delete administrator {email}?',
  'set.partner.deleteConfirm': 'Delete partner brand {name}?',
  'set.err.load': 'Failed to load settings',
  'set.ai.title': 'AI Infrastructure Copilot',
  'set.ai.url': 'Base API URL',
  'set.ai.model': 'Model Name',
  'set.ai.key': 'API Key',
  'set.ai.on': 'AI Copilot enabled',
  'ai.title': 'Infra Copilot',
  'ai.ask': 'Ask Copilot',
  'ai.askPh': 'Ask about nodes, users, telemetry...',
  'ai.send': 'Send',
  'ai.confirm': 'Approve',
  'ai.reject': 'Deny',
  'ai.executed': 'Action executed successfully.',
  'ai.cancelled': 'Action cancelled by operator.',
  'ai.denied': 'Access denied: AI Copilot is restricted to owner or authorized administrators.',
  'ai.offline': 'AI Copilot is not configured. Specify endpoint and API key in Settings.',
  'ai.providers': 'Quick Suggestions',
  'ai.chip1': 'Top 5 traffic consumers',
  'ai.chip2': 'Check node health across regions',
  'ai.chip3': 'Recommend sysctl BBR tuning',
  'ai.chatFailed': 'AI chat service unavailable',
  'ai.expiresIn': 'expires in',
  'ai.execFailed': 'Execution failed:',
  'cmdk.placeholder': 'Jump to nodes, users, plans, settings...',
  'cmdk.commands': 'Commands',
  'cmdk.nodes': 'Nodes',
  'cmdk.users': 'Users',
  'cmdk.plans': 'Plans',
  'cmdk.go': 'Navigate',
  'cmdk.cmd.addNode': 'Add Node',
  'cmdk.cmd.createUser': 'Create User',
  'cmdk.cmd.copilot': 'Open AI Copilot',
  'cmdk.cmd.theme': 'Toggle Theme',
} as const;

export type Key = keyof typeof en;

const ru: Record<Key, string> = {
  'app.brand': 'Панель управления',
  'app.version': '0.1.0v',
  'nav.dashboard': 'Обзор',
  'nav.users': 'Пользователи',
  'nav.nodes': 'Серверы (ноды)',
  'nav.plans': 'Тарифные планы',
  'nav.credentials': 'Ключи доступа',
  'nav.analytics': 'Трафик и логи',
  'nav.broadcast': 'Рассылки',
  'nav.audit': 'Журнал аудита',
  'nav.settings': 'Настройки и шлюзы',
  'nav.copilot': 'AI-ассистент',
  'nav.copilot.sub': 'Агент активен',
  'nav.official': 'Официальный канал',
  'nav.preview': 'версия v2 (react)',
  'nav.classic': 'классическая панель: /admin',
  'nav.logout': 'Выйти',
  'dash.title': 'Состояние кластера',
  'dash.subtitle': 'Мониторинг серверов и сетевая телеметрия в реальном времени',
  'dash.paused': 'пауза в фоне',
  'dash.active': 'КЛАСТЕР В ПОРЯДКЕ',
  'dash.cluster': 'КЛАСТЕР',
  'dash.unreachable': 'телеметрия недоступна',
  'dash.connecting': 'подключение...',
  'dash.retry': 'Сервер телеметрии недоступен. Проверьте связь с панелью управления и повторите попытку.',
  'dash.cpu': 'Нагрузка CPU',
  'dash.cpu.sub': 'Средняя нагрузка',
  'dash.cpu.host': 'хост cpu',
  'dash.mem': 'Оперативная память',
  'dash.disk': 'Дисковое хранилище',
  'dash.net': 'Сетевой поток',
  'dash.h.cpu': 'История нагрузки CPU',
  'dash.h.mem': 'История потребления памяти',
  'dash.h.disk': 'История использования диска',
  'dash.h.net': 'История пропускной способности сети',
  'dash.collapse': 'Свернуть',
  'dash.nodes': 'Активные серверы',
  'dash.nodes.sub': 'нод онлайн',
  'dash.users': 'Активные клиенты',
  'dash.users.registered': 'всего в базе',
  'dash.protoCount': 'Протоколы',
  'dash.protoCount.sub': 'WG • AWG • VLESS',
  'dash.traffic': 'Трафик за 30 дней',
  'dash.traffic.sub': 'Суммарный объём переданных данных',
  'dash.creds': 'Выдано ключей',
  'dash.creds.sub': 'по всем протоколам',
  'dash.throughput': 'Текущая скорость',
  'dash.in': 'входящий',
  'dash.out': 'исходящий',
  'dash.proto': 'Распределение протоколов',
  'dash.proto.sub': 'соотношение активных ключей по протоколам',
  'dash.proto.empty': 'Ключей пока нет',
  'dash.proto.emptyHint': 'Выпустите первый ключ, чтобы увидеть распределение протоколов',
  'dash.top': 'Лидеры по трафику',
  'dash.top.sub': 'пользователи с максимальным потреблением',
  'dash.allUsers': 'Все пользователи →',
  'dash.top.empty': 'Трафика пока нет',
  'dash.top.emptyHint': 'Статистика появится после первых подключений пользователей',
  'dash.fleet': 'Серверы кластера',
  'dash.fleet.sub': 'Телеметрия узлов и статус подключений в реальном времени',
  'dash.manage': 'Управление серверами',
  'dash.col.node': 'Сервер / Локация',
  'dash.col.status': 'Статус',
  'dash.col.host': 'Хост : Порт',
  'dash.col.proto': 'Протоколы',
  'dash.col.seen': 'Был на связи',
  'dash.col.actions': 'Действия',
  'dash.inspect': 'Подробнее →',
  'dash.fleet.empty': 'Выходные серверы ещё не добавлены. Запустите агент или добавьте ноду вручную.',
  'dash.global': 'Любой регион',
  'dash.unknown': 'неизвестно',
  'dash.never': 'Никогда',
  'dash.themeToggle': 'Сменить тему оформления',
  'dash.samplesLive': 'последние 40 точек · в реальном времени',
  'dash.chartMax': 'макс',
  'dash.chartNow': 'сейчас',
  'nodes.title': 'VPN-серверы',
  'nodes.subtitle': 'Управление парком нод и точками выхода',
  'nodes.total': 'Всего серверов:',
  'nodes.register': '+ Добавить сервер',
  'nodes.col.name': 'Название',
  'nodes.col.status': 'Статус',
  'nodes.col.endpoint': 'VPN Endpoint',
  'nodes.col.pubkey': 'Публичный ключ',
  'nodes.col.grpc': 'Панель управления (gRPC)',
  'nodes.col.heartbeat': 'Пинг (Heartbeat)',
  'nodes.col.actions': 'Действия',
  'nodes.inspect': 'Обзор',
  'nodes.delete': 'Удалить',
  'nodes.confirmTitle': 'Удаление сервера',
  'nodes.deleteConfirm': 'Удалить сервер "{name}"? Все активные соединения на этом узле будут разорваны.',
  'nodes.err.load': 'Не удалось загрузить список серверов',
  'nodes.err.register': 'Не удалось зарегистрировать сервер',
  'nodes.err.delete': 'Не удалось удалить сервер',
  'nodes.empty': 'Серверы не найдены.',
  'nodes.modal.title': 'Регистрация VPN-сервера',
  'nodes.modal.name': 'Имя сервера',
  'nodes.modal.namePh': 'например: de-frankfurt-01',
  'nodes.modal.region': 'Регион / Страна',
  'nodes.modal.regionPh': 'например: EU-DE',
  'nodes.modal.host': 'Публичный IP или домен',
  'nodes.modal.hostPh': 'например: 217.26.25.6',
  'nodes.modal.port': 'Порт',
  'nodes.modal.pubkey': 'Публичный ключ WireGuard',
  'nodes.modal.pubkeyPh': 'Ключ в формате Base64',
  'nodes.modal.cancel': 'Отмена',
  'nodes.modal.save': 'Сохранить сервер',
  'users.title': 'Пользователи и подписки',
  'users.subtitle': 'Лимиты трафика, тарифы и универсальные ссылки подключения',
  'users.seg.all': 'Все пользователи',
  'users.seg.active': 'Активные подписки',
  'users.seg.lead': 'Лиды бота',
  'users.seg.trial': 'Пробный период',
  'users.seg.expired': 'Истёкшие',
  'users.seg.banned': 'Заблокированные',
  'users.create': '+ Создать пользователя',
  'users.col.user': 'Пользователь / Контакт',
  'users.col.life': 'Статус',
  'users.col.quota': 'Лимит трафика',
  'users.col.token': 'Токен подписки',
  'users.col.exp': 'Срок действия',
  'users.col.actions': 'Действия',
  'users.noEmail': 'email не привязан',
  'users.editEmail': '[Изменить Email]',
  'users.seen': 'Был онлайн',
  'users.unlimited': 'Безлимитно',
  'users.permanent': 'Бессрочно',
  'users.plan': 'Тариф',
  'users.lead': 'Лид бота',
  'users.custom': 'Индивидуальный',
  'users.message': 'Написать',
  'users.assign': 'Назначить тариф',
  'users.reset': 'Сбросить трафик',
  'users.ban': 'Заблокировать',
  'users.unban': 'Разблокировать',
  'users.delete': 'Удалить',
  'users.empty': 'В этой категории пользователей нет.',
  'users.delTitle': 'Удаление пользователя',
  'users.deleteConfirm': 'Удалить пользователя "{name}"? Все привязанные ключи доступа будут отозваны навсегда.',
  'users.err.load': 'Не удалось загрузить список пользователей',
  'users.err.action': 'Не удалось выполнить операцию',
  'users.tip.id': 'Внутренний ID',
  'users.tip.openTg': 'Открыть профиль в Telegram',
  'users.tip.viewSub': 'Универсальная ссылка и QR-код подписки',
  'users.tip.resetQuota': 'Сбросить израсходованный трафик',
  'users.tip.ban': 'Заблокировать пользователя',
  'users.tip.unban': 'Разблокировать пользователя',
  'users.tip.message': 'Отправить личное сообщение в Telegram',
  'users.tip.assign': 'Назначить или подарить тариф',
  'users.trialDuration': 'ПРОБНЫЙ ПЕРИОД ({hours} ч)',
  'users.st.active': 'Активен',
  'users.st.lead': 'Лид',
  'users.st.trial': 'Триал',
  'users.st.expired': 'Истёк',
  'users.st.banned': 'Заблокирован',
  'users.qr.title': 'Универсальная подписка',
  'users.qr.user': 'Пользователь: ',
  'users.qr.scan': 'Отсканируйте в Sing-box, V2Ray, Happ, Hiddify или Amnezia',
  'users.qr.url': 'Универсальная ссылка на подписку',
  'users.qr.copy': 'Скопировать ссылку',
  'users.qr.copied': 'Ссылка скопирована в буфер обмена!',
  'users.qr.raw': 'Открыть конфиг ↗',
  'users.c.title': 'Новая подписка клиента',
  'users.c.sub': 'Выпуск универсальных ключей VPN и настройка профиля подписки',
  'users.c.username': 'Имя пользователя (логин)',
  'users.c.usernamePh': 'например: alex_smith',
  'users.c.email': 'Email (необязательно)',
  'users.c.tgId': 'Telegram User ID (необязательно)',
  'users.c.tgIdHint': 'Числовой ID для синхронизации с Telegram-ботом',
  'users.c.tgUser': 'Telegram @username (необязательно)',
  'users.c.tgUserHint': 'Без символа @',
  'users.c.mode': 'Режим назначения тарифа',
  'users.c.preset': 'Готовый тариф из каталога',
  'users.c.custom': 'Индивидуальные параметры',
  'users.c.plan': 'Выберите тариф',
  'users.c.noPlans': 'В каталоге пока нет тарифов. Переключитесь в индивидуальный режим.',
  'users.c.duration': 'Срок действия (дней)',
  'users.c.durationHint': 'Период подписки до необходимости продления',
  'users.c.limit': 'Лимит трафика (ГБ)',
  'users.c.unlimited': 'Без ограничений по трафику',
  'users.c.validity': 'Срок действия (дней)',
  'users.c.never': 'Бессрочный доступ',
  'users.c.note': 'Примечание (необязательно)',
  'users.c.notePh': 'например: VIP-клиент, тестовый доступ',
  'users.c.cancel': 'Отмена',
  'users.c.create': 'Создать подписку',
  'users.dm.title': 'Прямое сообщение в Telegram',
  'users.dm.sub': 'Персональное уведомление клиенту от имени бота',
  'users.dm.text': 'Текст сообщения (поддерживается HTML-разметка)',
  'users.dm.send': 'Отправить сообщение',
  'users.assign.title': 'Назначить или подарить тариф',
  'users.assign.sub': 'Применение тарифного плана и обновление квоты трафика',
  'users.assign.plan': 'Выберите тарифный план',
  'users.assign.duration': 'Срок (дней)',
  'users.assign.durationHint': 'Новый срок действия рассчитывается от сегодняшнего дня.',
  'users.assign.notify': 'Отправить клиенту уведомление о продлении в Telegram',
  'users.assign.go': 'Применить тариф',
  'users.email.title': 'Привязать Email пользователя',
  'users.email.sub': 'Почтовый адрес для восстановления доступа к подписке',
  'users.email.label': 'Адрес электронной почты',
  'users.email.save': 'Сохранить Email',
  'plans.title': 'Тарифные планы',
  'plans.subtitle': 'Лимиты трафика, периоды подписок, цены и протоколы',
  'plans.count': 'Всего тарифов:',
  'plans.new': '+ Новый тариф',
  'plans.trial': 'ПРОБНЫЙ ПЕРИОД',
  'plans.bandwidth': 'Трафик:',
  'plans.unlimited': 'Безлимитно',
  'plans.devices': 'Одновременных устройств:',
  'plans.devicesUnit': 'устр.',
  'plans.trialDur': 'Длительность триала:',
  'plans.hours': 'ч.',
  'plans.durations': 'Цены по периодам:',
  'plans.edit': 'Редактировать',
  'plans.remove': 'Удалить',
  'plans.readonly': 'Системный тариф',
  'plans.empty': 'Тарифные планы ещё не созданы. Добавьте тариф, чтобы связывать квоты с клиентами.',
  'plans.delTitle': 'Удаление тарифа',
  'plans.deleteConfirm': 'Удалить тарифный план "{name}"? Текущие подписчики этого тарифа сохранят доступ.',
  'plans.err.load': 'Не удалось загрузить список тарифов',
  'plans.err.delete': 'Не удалось удалить тариф',
  'plans.perMonth': '/мес',
  'plans.dynamic': 'Авто',
  'plans.d1': '1 мес:',
  'plans.d3': '3 мес:',
  'plans.d6': '6 мес:',
  'plans.d12': '12 мес:',
  'plans.c.title': 'Конструктор: Создание тарифа',
  'plans.c.sub': 'Настройка протоколов, лимита устройств, квот и стоимости по периодам',
  'plans.c.name': 'Название тарифа',
  'plans.c.protos': 'Разрешённые протоколы',
  'plans.c.limit': 'Лимит трафика (ГБ)',
  'plans.c.limitHint': 'Укажите 0 для полного безлимита',
  'plans.c.devices': 'Максимум устройств',
  'plans.c.devicesHint': 'Максимальное число одновременно подключенных ключей/устройств',
  'plans.c.trial': 'Сделать бесплатным пробным тарифом',
  'plans.c.trialHours': 'Длительность триала (в часах)',
  'plans.c.trialHint': 'Новые пользователи бота получат этот тариф бесплатно при первом запуске.',
  'plans.c.pricing': 'Стоимость по периодам (USD)',
  'plans.c.p1': 'Цена за 1 месяц',
  'plans.c.p3': 'Цена за 3 месяца',
  'plans.c.p6': 'Цена за 6 месяцев',
  'plans.c.p12': 'Цена за 12 месяцев',
  'plans.c.auto': 'Оставьте пустым для автоскидки',
  'plans.c.stars': 'Цена в Telegram Stars',
  'plans.c.free': '100% бесплатный тариф: оплата в USD и Stars отключена для триал-периода.',
  'plans.c.cancel': 'Отмена',
  'plans.c.save': 'Сохранить тариф',
  'plans.e.title': 'Конструктор: Редактирование тарифа',
  'plans.e.updating': 'Редактирование тарифа: ',
  'plans.e.update': 'Обновить тариф',
  'creds.title': 'Ключи доступа',
  'creds.subtitle': 'Ключевые пары клиентов и конфигурации туннелей',
  'creds.total': 'Всего ключей:',
  'creds.col.user': 'Пользователь',
  'creds.col.proto': 'Протокол',
  'creds.col.ipv4': 'Туннельный IPv4',
  'creds.col.key': 'Публичный ключ / UUID',
  'creds.col.status': 'Статус',
  'creds.col.actions': 'Действия',
  'creds.vless': 'Клиент VLESS',
  'creds.uuid': 'UUID / Flow назначен',
  'creds.rotate': 'Перевыпустить',
  'creds.rotateTitle': 'Сгенерировать новую ключевую пару для клиента',
  'creds.revoke': 'Отозвать',
  'creds.delTitle': 'Отозвать ключ доступа',
  'creds.deleteConfirm': 'Отозвать этот ключ доступа? Подключение клиента будет немедленно прекращено.',
  'creds.err.load': 'Не удалось загрузить ключи доступа',
  'creds.err.action': 'Не удалось выполнить действие с ключом',
  'creds.empty': 'Ключи доступа ещё не созданы.',
  'analytics.title': 'Аналитика трафика и журнал аудита',
  'analytics.subtitle': 'Графики сетевой пропускной способности и фиксация действий операторов',
  'analytics.rx': 'Входящий поток (RX)',
  'analytics.rx.sub': 'Суммарный объём загрузки из интернета',
  'analytics.tx': 'Исходящий поток (TX)',
  'analytics.tx.sub': 'Суммарный объём отдачи клиентам',
  'analytics.total': 'Общий объём трафика',
  'analytics.total.sub': 'Суммарный объём сетевого ввода/вывода',
  'analytics.trail': 'Журнал системных действий',
  'analytics.trail.sub': 'Зафиксированные действия администраторов и события безопасности',
  'analytics.full': 'Полный журнал аудита →',
  'analytics.col.time': 'Время',
  'analytics.col.action': 'Действие',
  'analytics.col.resource': 'Ресурс',
  'analytics.col.details': 'Детали / Изменения',
  'analytics.col.ip': 'IP-адрес',
  'analytics.col.inspect': 'Просмотр',
  'analytics.empty': 'Записей аудита пока нет.',
  'analytics.modal': 'Просмотр записи аудита',
  'analytics.payload': 'ДАННЫЕ',
  'analytics.close': 'Закрыть',
  'analytics.internal': 'Внутренний',
  'analytics.system': 'система',
  'analytics.alertBadge': 'ПРЕДУПРЕЖДЕНИЕ БЕЗОПАСНОСТИ',
  'audit.title': 'Журнал аудита администраторов',
  'audit.subtitle': 'Изменения прав доступа, настройки и защищённый от перезаписи лог событий',
  'audit.filterAction': 'Фильтр по действию (например: DirectMessageUser)...',
  'audit.filterResource': 'Фильтр по ресурсу (например: user, admin)...',
  'audit.apply': 'Применить фильтр',
  'audit.stored': 'записей зафиксировано (защищённое WORM-хранилище)',
  'audit.retention': 'Настройка срока хранения и записи событий',
  'login.title': 'Панель управления',
  'login.subtitle': 'Авторизация в панели управления VPN',
  'login.user': 'Логин или Email',
  'login.userPh': 'admin@example.com',
  'login.pass': 'Пароль',
  'login.totp': 'Код 2FA (TOTP)',
  'login.totpHint': '(если включён)',
  'login.go': 'Войти в систему',
  'login.failed': 'Не удалось войти. Проверьте правильность логина, пароля или кода 2FA.',
  'nd.back': '← Назад к серверам',
  'nd.drain': 'Вывести из ротации (Drain)',
  'nd.online': 'Ввести в работу (Online)',
  'nd.telemetry': 'Аппаратная телеметрия и нагрузка',
  'nd.protos': 'Настроенные протоколы и сервисы',
  'nd.peers': 'Ключи и клиенты на узле',
  'nd.col.user': 'Пользователь',
  'nd.col.proto': 'Протокол',
  'nd.col.ipv4': 'Выделенный IPv4',
  'nd.col.key': 'Публичный ключ / UUID',
  'nd.col.status': 'Статус',
  'nd.empty': 'К этому серверу ещё не привязано ни одного ключа.',
  'nd.grpc': 'gRPC:',
  'nd.offline': 'Агент не в сети',
  'nd.offlineHint': 'Телеметрия появится сразу после подключения агента сервера',
  'nd.proto.wgDesc': 'Интерфейс: wg0',
  'nd.proto.awgDesc': 'Включена маскировка мусорными пакетами и заголовками',
  'nd.proto.vlessDesc': 'SNI: dl.google.com • Flow: xtls-rprx-vision',
  'bc.title': 'Центр рассылок и оповещений',
  'bc.subtitle': 'Таргетированные Telegram-оповещения с контролем скорости отправки',
  'bc.sent': 'Рассылка поставлена в очередь и отправляется в фоновом режиме (~25 сообщ./сек).',
  'bc.compose': 'Новая кампания',
  'bc.cTitle': 'Название кампании',
  'bc.cTitlePh': 'например: Плановые технические работы',
  'bc.segment': 'Целевая аудитория (сегмент)',
  'bc.seg.all': 'Все пользователи (активные, триал, лиды и истёкшие)',
  'bc.seg.leads': 'Лиды бота (запустили бота, но не оплатили подписку)',
  'bc.seg.active': 'Только активные клиенты',
  'bc.seg.expired': 'Клиенты с истёкшей подпиской',
  'bc.body': 'Текст сообщения (поддерживается HTML / Markdown)',
  'bc.bodyPh': 'Введите текст объявления для пользователей...',
  'bc.btnBox': 'Инлайн-кнопка действия (необязательно)',
  'bc.btnLabel': 'Текст на кнопке',
  'bc.btnLabelPh': 'например: Продлить доступ',
  'bc.btnUrl': 'Ссылка для перехода',
  'bc.note': 'Сообщения отправляются асинхронно через Telegram Bot API с контролем скорости (~25 сообщ./сек), исключая превышение лимитов Telegram.',
  'bc.dispatch': 'Запустить рассылку',
  'bc.history': 'История рассылок',
  'bc.total': 'Всего кампаний:',
  'bc.col.title': 'Кампания / Сегмент',
  'bc.col.status': 'Статус',
  'bc.col.sent': 'Доставлено / Всего',
  'bc.col.failed': 'Ошибок',
  'bc.col.created': 'Создана',
  'bc.segmentLbl': 'Сегмент:',
  'bc.empty': 'Кампаний рассылки пока не проводилось.',
  'bc.status.completed': 'ЗАВЕРШЕНО',
  'bc.status.sending': 'ОТПРАВЛЯЕТСЯ',
  'bc.status.failed': 'ОШИБКА',
  'bc.status.pending': 'В ОЧЕРЕДИ',
  'bc.err.csrf': 'Ошибка безопасности (CSRF)',
  'bc.err.create': 'Не удалось создать кампанию рассылки',
  'set.title': 'Настройки и интеграции',
  'set.subtitle': 'Администраторы, платёжные шлюзы, тексты бота и параметры безопасности',
  'set.billing': 'Биллинг и платёжные шлюзы',
  'set.billing.sub': 'Приём платежей, реквизиты API и обработка вебхуков',
  'set.replies': 'Тексты и ответы бота',
  'set.replies.sub': 'Онбординг клиентов, воронка конверсии и шаблоны сообщений',
  'set.referrals': 'Реферальная программа',
  'set.referrals.sub': 'Виральный рост, условия начислений и защита от накруток',
  'set.security': 'Политика Email и безопасность',
  'set.security.sub': 'Защита аккаунтов, OTP-коды по почте и настройки SMTP',
  'set.partners': 'Партнёры, Mini Apps и White-Label',
  'set.partners.sub': 'Выделенные боты, обязательная подписка на канал и Telegram Mini Apps',
  'set.open': 'Открыть →',
  'set.tab.admins': 'Администраторы и API-ключи',
  'set.tab.billing': 'Биллинг',
  'set.tab.replies': 'Ответы бота',
  'set.tab.referrals': 'Рефералы',
  'set.tab.security': 'Безопасность',
  'set.tab.partners': 'Партнёры',
  'set.tab.ai': 'AI-ассистент',
  'set.save': 'Сохранить',
  'set.saved': 'Настройки сохранены.',
  'set.failed': 'Не удалось сохранить настройки.',
  'set.admins': 'Администраторы системы',
  'set.addAdmin': 'Добавить администратора',
  'set.email': 'Email',
  'set.password': 'Пароль',
  'set.role': 'Роль',
  'set.add': 'Добавить',
  'set.cancel': 'Отмена',
  'set.delete': 'Удалить',
  'set.keys': 'API-ключи для разработчиков',
  'set.issueKey': 'Создать API-ключ',
  'set.keyName': 'Описание ключа',
  'set.keyNamePh': 'например: Bot-Service-Key',
  'set.scope': 'Права доступа (Scope)',
  'set.scope.admin': 'admin (Полный контроль над системой)',
  'set.scope.read': 'read (Только просмотр телеметрии)',
  'set.scope.write': 'write (Управление серверами и пользователями)',
  'set.generate': 'Сгенерировать ключ',
  'set.copyToken': 'Copy Token',
  'set.totp': 'Двухфакторная аутентификация (2FA)',
  'set.totpSetup': 'Настроить в классической консоли',
  'set.totpOn': 'Включена',
  'set.totpOff': 'Выключена',
  'set.disable': 'Отключить',
  'set.billing.title': 'Биллинг и платёжные шлюзы',
  'set.billing.crypto': 'API-токен CryptoBot',
  'set.billing.cryptoOn': 'CryptoBot включён',
  'set.billing.starsOn': 'Оплата через Telegram Stars включена',
  'set.billing.starsPrice': 'Цена в Stars за 1 месяц',
  'set.billing.webhook': 'Секретный ключ вебхука',
  'set.billing.sales': 'Токен бота продаж',
  'set.billing.alert': 'Токен бота оповещений',
  'set.billing.alertChat': 'ID чата для оповещений',
  'set.billing.alertOn': 'Оповещения включены',
  'set.gateways': 'Подключенные платёжные шлюзы',
  'set.gw.name': 'Название шлюза',
  'set.gw.token': 'Токен API',
  'set.gw.enable': 'Включён',
  'set.gw.add': 'Добавить шлюз',
  'set.gw.toggle': 'Переключить',
  'set.gw.on': 'вкл',
  'set.gw.off': 'выкл',
  'set.replies.title': 'Ответы Telegram-бота и клиентский путь',
  'set.replies.bot': 'Токен Telegram-бота и брендинг',
  'set.replies.botToken': 'Токен бота',
  'set.replies.maskedHint': 'оставьте маску, чтобы не менять',
  'set.replies.channel': 'Ссылка на канал',
  'set.replies.support': 'Ссылка на поддержку',
  'set.replies.welcome': 'Приветственный текст',
  'set.replies.templates': 'шаблонов',
  'set.replies.mediaUrl': 'Image / GIF URL (optional)',
  'set.replies.mediaFile': '... or upload an image (max 15MB)',
  'set.replies.bannerTitle': 'Master Welcome Banner',
  'set.replies.bannerUrl': 'Banner image URL',
  'set.replies.bannerFile': '... or upload a banner (max 15MB)',
  'set.replies.placeholders': 'Placeholders — click to append to the last edited template:',
  'set.replies.preview': 'Live Telegram Preview',
  'set.replies.previewHint': 'Mock preview — placeholders filled with demo values',
  'set.ref.title': 'Реферальная программа и виральный рост',
  'set.ref.on': 'Реферальная программа включена',
  'set.ref.model': 'Модель вознаграждения',
  'set.ref.inviter': 'Бонусные дни пригласившему',
  'set.ref.invitee': 'Бонусные дни приглашённому другу',
  'set.ref.commission': 'Процент партнёрского вознаграждения (%)',
  'set.ref.min': 'Минимальная сумма покупки',
  'set.ref.qual': 'Условие начисления бонуса',
  'set.ref.cap': 'Дневной лимит бонусов',
  'set.ref.expired': 'Начислять бонусы аккаунтам с истёкшей подпиской',
  'set.sec.title': 'Политика Email и безопасность',
  'set.sec.policy': 'Режим обязательности Email',
  'set.sec.policyLabel': 'Политика Email (необязательно / обязательно / выключено)',
  'set.sec.otp': 'Подтверждение Email кодом (OTP)',
  'set.sec.smtp': 'Почтовый движок (SMTP / Симуляция)',
  'set.sec.host': 'SMTP-сервер (Хост)',
  'set.sec.port': 'Порт SMTP',
  'set.sec.user': 'Имя пользователя SMTP',
  'set.sec.pass': 'Пароль SMTP',
  'set.sec.from': 'Email отправителя (From)',
  'set.sec.sim': 'Симуляция отправки (реальные письма не отсылаются)',
  'set.retention': 'Срок хранения журнала аудита',
  'set.retention.sub': 'Категории записываемых событий и глубина хранения истории.',
  'set.retention.days': 'Дней хранения (0 = бессрочно)',
  'set.partners.title': 'Партнёрские бренды и White-Label',
  'set.partners.add': 'Добавить партнёрский бренд и бота',
  'set.partners.name': 'Название бренда',
  'set.partners.slug': 'Идентификатор (Slug)',
  'set.partners.token': 'Токен бота',
  'set.partners.username': 'Юзернейм бота',
  'set.partners.channel': 'Ссылка на канал',
  'set.partners.support': 'Ссылка на поддержку',
  'set.partners.domain': 'Собственный домен',
  'set.partners.miniapp': 'URL Telegram Mini App',
  'set.partners.welcome': 'Приветственное сообщение',
  'set.partners.require': 'Требовать обязательную подписку на канал',
  'set.partners.empty': 'Партнёрские бренды ещё не настроены.',
  'set.admin.deleteConfirm': 'Удалить администратора {email}?',
  'set.partner.deleteConfirm': 'Удалить партнёра "{name}"?',
  'set.err.load': 'Не удалось загрузить настройки',
  'set.ai.title': 'AI-ассистент инфраструктуры',
  'set.ai.url': 'Базовый URL API',
  'set.ai.model': 'Модель',
  'set.ai.key': 'API-ключ',
  'set.ai.on': 'AI-ассистент включён',
  'ai.title': 'AI-ассистент инфраструктуры',
  'ai.ask': 'Спросить ассистента',
  'ai.askPh': 'Спросите о серверах, пользователях, телеметрии...',
  'ai.send': 'Отправить',
  'ai.confirm': 'Подтвердить',
  'ai.reject': 'Отклонить',
  'ai.executed': 'Действие успешно выполнено.',
  'ai.cancelled': 'Действие отменено оператором.',
  'ai.denied': 'Доступ запрещён: AI-ассистент доступен только владельцу или уполномоченным администраторам.',
  'ai.offline': 'AI-ассистент не настроен. Укажите эндпоинт и API-ключ в настройках.',
  'ai.providers': 'Быстрые команды',
  'ai.chip1': 'Топ-5 пользователей по трафику',
  'ai.chip2': 'Проверить состояние серверов по регионам',
  'ai.chip3': 'Рекомендовать оптимизацию sysctl BBR',
  'ai.chatFailed': 'Сервис AI-ассистента временно недоступен',
  'ai.expiresIn': 'истекает через',
  'ai.execFailed': 'Ошибка выполнения:',
  'cmdk.placeholder': 'Быстрый переход к серверам, пользователям, тарифам...',
  'cmdk.commands': 'Команды',
  'cmdk.nodes': 'Серверы',
  'cmdk.users': 'Пользователи',
  'cmdk.plans': 'Тарифы',
  'cmdk.go': 'Перейти',
  'cmdk.cmd.addNode': 'Добавить сервер',
  'cmdk.cmd.createUser': 'Создать пользователя',
  'cmdk.cmd.copilot': 'Открыть AI-ассистента',
  'cmdk.cmd.theme': 'Переключить тему оформления',
};

const LangCtx = createContext<{
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (k: Key, params?: Record<string, string | number>) => string;
}>({
  lang: 'ru',
  setLang: () => {},
  t: (k) => k,
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const v = localStorage.getItem('vpn_lang');
    return v === 'en' ? 'en' : 'ru';
  });
  const setLang = (l: Lang) => {
    localStorage.setItem('vpn_lang', l);
    setLangState(l);
  };
  const t = (k: Key, params?: Record<string, string | number>): string => {
    let str = (lang === 'ru' ? ru[k] : en[k]) || en[k] || k;
    if (params) {
      for (const [pk, pv] of Object.entries(params)) {
        str = str.replace(new RegExp(`\\{${pk}\\}`, 'g'), String(pv));
      }
    }
    return str;
  };
  return <LangCtx.Provider value={{ lang, setLang, t }}>{children}</LangCtx.Provider>;
}

export function useLang() {
  return useContext(LangCtx);
}

export function LangToggle() {
  const { lang, setLang } = useLang();
  return (
    <div className="tabular-nums flex overflow-hidden rounded-lg border border-[var(--border-subtle)] text-[11px] font-semibold">
      {(['en', 'ru'] as Lang[]).map((l) => (
        <button
          key={l}
          onClick={() => setLang(l)}
          className={`px-2.5 py-1 uppercase transition-colors ${
            lang === l
              ? 'bg-[var(--bg-hover)] text-[var(--text-primary)]'
              : 'text-[var(--text-muted)] hover:text-[var(--text-secondary)]'
          }`}
        >
          {l}
        </button>
      ))}
    </div>
  );
}

