// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (email, password_hash, role, totp_secret)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, role, totp_secret, last_login, created_at, COALESCE(permissions, '{}'::jsonb), must_change_password
`

type CreateAdminParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Role         pgtype.Text `json:"role"`
	TotpSecret   pgtype.Text `json:"totp_secret"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRow(ctx, createAdmin,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.TotpSecret,
	)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.TotpSecret,
		&i.LastLogin,
		&i.CreatedAt,
		&i.Permissions,
		&i.MustChangePassword,
	)
	return i, err
}

const deleteAdmin = `-- name: DeleteAdmin :exec
DELETE FROM admins WHERE id = $1
`

func (q *Queries) DeleteAdmin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAdmin, id)
	return err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, password_hash, role, totp_secret, last_login, created_at, COALESCE(permissions, '{}'::jsonb), must_change_password FROM admins WHERE email = $1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.TotpSecret,
		&i.LastLogin,
		&i.CreatedAt,
		&i.Permissions,
		&i.MustChangePassword,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, email, password_hash, role, totp_secret, last_login, created_at, COALESCE(permissions, '{}'::jsonb), must_change_password FROM admins WHERE id = $1
`

func (q *Queries) GetAdminByID(ctx context.Context, id uuid.UUID) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.TotpSecret,
		&i.LastLogin,
		&i.CreatedAt,
		&i.Permissions,
		&i.MustChangePassword,
	)
	return i, err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, email, password_hash, role, totp_secret, last_login, created_at, COALESCE(permissions, '{}'::jsonb), must_change_password FROM admins ORDER BY created_at DESC
`

func (q *Queries) ListAdmins(ctx context.Context) ([]Admin, error) {
	rows, err := q.db.Query(ctx, listAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Admin{}
	for rows.Next() {
		var i Admin
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.TotpSecret,
			&i.LastLogin,
			&i.CreatedAt,
			&i.Permissions,

			&i.MustChangePassword,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdmin = `-- name: UpdateAdmin :one
UPDATE admins
SET email = $2, password_hash = $3, role = $4, totp_secret = $5, last_login = $6
WHERE id = $1
RETURNING id, email, password_hash, role, totp_secret, last_login, created_at, COALESCE(permissions, '{}'::jsonb), must_change_password
`

type UpdateAdminParams struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         pgtype.Text        `json:"role"`
	TotpSecret   pgtype.Text        `json:"totp_secret"`
	LastLogin    pgtype.Timestamptz `json:"last_login"`
}

func (q *Queries) UpdateAdmin(ctx context.Context, arg UpdateAdminParams) (Admin, error) {
	row := q.db.QueryRow(ctx, updateAdmin,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.TotpSecret,
		arg.LastLogin,
	)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.TotpSecret,
		&i.LastLogin,
		&i.CreatedAt,
		&i.Permissions,
		&i.MustChangePassword,
	)
	return i, err
}

const updateAdminLastLogin = `-- name: UpdateAdminLastLogin :exec
UPDATE admins SET last_login = now() WHERE id = $1
`

func (q *Queries) UpdateAdminLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAdminLastLogin, id)
	return err
}

const updateAdminPermissions = `-- name: UpdateAdminPermissions :exec
UPDATE admins SET permissions = $2 WHERE id = $1
`

func (q *Queries) UpdateAdminPermissions(ctx context.Context, id uuid.UUID, permissions []byte) error {
	_, err := q.db.Exec(ctx, updateAdminPermissions, id, permissions)
	return err
}
