// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package store

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs
WHERE ($1::uuid IS NULL OR $1::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR admin_id = $1)
AND ($2 = '' OR action = $2)
AND ($3 = '' OR resource_type = $3)
AND created_at >= $4 AND created_at <= $5
`

type CountAuditLogsParams struct {
	Column1     uuid.UUID          `json:"column_1"`
	Column2     interface{}        `json:"column_2"`
	Column3     interface{}        `json:"column_3"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.CreatedAt,
		arg.CreatedAt_2,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (admin_id, api_key_id, action, resource_type, resource_id, diff, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, admin_id, api_key_id, action, resource_type, resource_id, diff, ip_address, user_agent, created_at
`

type CreateAuditLogParams struct {
	AdminID      pgtype.UUID `json:"admin_id"`
	ApiKeyID     pgtype.UUID `json:"api_key_id"`
	Action       string      `json:"action"`
	ResourceType pgtype.Text `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
	Diff         []byte      `json:"diff"`
	IpAddress    *netip.Addr `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.AdminID,
		arg.ApiKeyID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Diff,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.ApiKeyID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Diff,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, admin_id, api_key_id, action, resource_type, resource_id, diff, ip_address, user_agent, created_at FROM audit_logs
WHERE ($1::uuid IS NULL OR $1::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR admin_id = $1)
AND ($2 = '' OR action = $2)
AND ($3 = '' OR resource_type = $3)
AND created_at >= $4 AND created_at <= $5
ORDER BY created_at DESC
LIMIT $6 OFFSET $7
`

type ListAuditLogsParams struct {
	Column1     uuid.UUID          `json:"column_1"`
	Column2     interface{}        `json:"column_2"`
	Column3     interface{}        `json:"column_3"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	Limit       int32              `json:"limit"`
	Offset      int32              `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.ApiKeyID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Diff,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAuditLogsOlderThan = `-- name: DeleteAuditLogsOlderThan :exec
DELETE FROM audit_logs
WHERE created_at < $1
`

func (q *Queries) DeleteAuditLogsOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteAuditLogsOlderThan, createdAt)
	return err
}

