// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBroadcastCampaign = `-- name: CreateBroadcastCampaign :one
INSERT INTO broadcast_campaigns (title, target_segment, message_text, inline_buttons, total_recipients, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, target_segment, message_text, inline_buttons, total_recipients, sent_count, failed_count, status, created_at, completed_at
`

type CreateBroadcastCampaignParams struct {
	Title           string      `json:"title"`
	TargetSegment   string      `json:"target_segment"`
	MessageText     string      `json:"message_text"`
	InlineButtons   []byte      `json:"inline_buttons"`
	TotalRecipients pgtype.Int4 `json:"total_recipients"`
	Status          pgtype.Text `json:"status"`
}

func (q *Queries) CreateBroadcastCampaign(ctx context.Context, arg CreateBroadcastCampaignParams) (BroadcastCampaign, error) {
	row := q.db.QueryRow(ctx, createBroadcastCampaign,
		arg.Title,
		arg.TargetSegment,
		arg.MessageText,
		arg.InlineButtons,
		arg.TotalRecipients,
		arg.Status,
	)
	var i BroadcastCampaign
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TargetSegment,
		&i.MessageText,
		&i.InlineButtons,
		&i.TotalRecipients,
		&i.SentCount,
		&i.FailedCount,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, plan_id, gateway, external_invoice_id, amount, currency, status, duration_months, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, plan_id, gateway, external_invoice_id, amount, currency, status, duration_months, metadata, paid_at, created_at, updated_at
`

type CreateOrderParams struct {
	UserID            uuid.UUID      `json:"user_id"`
	PlanID            uuid.UUID      `json:"plan_id"`
	Gateway           string         `json:"gateway"`
	ExternalInvoiceID pgtype.Text    `json:"external_invoice_id"`
	Amount            pgtype.Numeric `json:"amount"`
	Currency          string         `json:"currency"`
	Status            pgtype.Text    `json:"status"`
	DurationMonths    pgtype.Int4    `json:"duration_months"`
	Metadata          []byte         `json:"metadata"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.PlanID,
		arg.Gateway,
		arg.ExternalInvoiceID,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.DurationMonths,
		arg.Metadata,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Gateway,
		&i.ExternalInvoiceID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.DurationMonths,
		&i.Metadata,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPromoCode = `-- name: CreatePromoCode :one
INSERT INTO promo_codes (code, discount_percent, discount_amount, bonus_days, bonus_bytes, max_uses, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, code, discount_percent, discount_amount, bonus_days, bonus_bytes, max_uses, used_count, is_active, expires_at, created_at
`

type CreatePromoCodeParams struct {
	Code            string             `json:"code"`
	DiscountPercent pgtype.Int4        `json:"discount_percent"`
	DiscountAmount  pgtype.Numeric     `json:"discount_amount"`
	BonusDays       pgtype.Int4        `json:"bonus_days"`
	BonusBytes      pgtype.Int8        `json:"bonus_bytes"`
	MaxUses         pgtype.Int4        `json:"max_uses"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePromoCode(ctx context.Context, arg CreatePromoCodeParams) (PromoCode, error) {
	row := q.db.QueryRow(ctx, createPromoCode,
		arg.Code,
		arg.DiscountPercent,
		arg.DiscountAmount,
		arg.BonusDays,
		arg.BonusBytes,
		arg.MaxUses,
		arg.ExpiresAt,
	)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountPercent,
		&i.DiscountAmount,
		&i.BonusDays,
		&i.BonusBytes,
		&i.MaxUses,
		&i.UsedCount,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getBillingSettings = `-- name: GetBillingSettings :one
SELECT cryptobot_api_token, cryptobot_enabled, telegram_stars_enabled, stars_price_per_month, webhook_secret, updated_at
FROM billing_settings
WHERE id = 1
`

type GetBillingSettingsRow struct {
	CryptobotApiToken    string             `json:"cryptobot_api_token"`
	CryptobotEnabled     bool               `json:"cryptobot_enabled"`
	TelegramStarsEnabled bool               `json:"telegram_stars_enabled"`
	StarsPricePerMonth   int32              `json:"stars_price_per_month"`
	WebhookSecret        string             `json:"webhook_secret"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetBillingSettings(ctx context.Context) (GetBillingSettingsRow, error) {
	row := q.db.QueryRow(ctx, getBillingSettings)
	var i GetBillingSettingsRow
	err := row.Scan(
		&i.CryptobotApiToken,
		&i.CryptobotEnabled,
		&i.TelegramStarsEnabled,
		&i.StarsPricePerMonth,
		&i.WebhookSecret,
		&i.UpdatedAt,
	)
	return i, err
}

const getBroadcastCampaignByID = `-- name: GetBroadcastCampaignByID :one
SELECT id, title, target_segment, message_text, inline_buttons, total_recipients, sent_count, failed_count, status, created_at, completed_at FROM broadcast_campaigns WHERE id = $1
`

func (q *Queries) GetBroadcastCampaignByID(ctx context.Context, id uuid.UUID) (BroadcastCampaign, error) {
	row := q.db.QueryRow(ctx, getBroadcastCampaignByID, id)
	var i BroadcastCampaign
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TargetSegment,
		&i.MessageText,
		&i.InlineButtons,
		&i.TotalRecipients,
		&i.SentCount,
		&i.FailedCount,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getOrderByExternalInvoiceID = `-- name: GetOrderByExternalInvoiceID :one
SELECT id, user_id, plan_id, gateway, external_invoice_id, amount, currency, status, duration_months, metadata, paid_at, created_at, updated_at FROM orders WHERE external_invoice_id = $1
`

func (q *Queries) GetOrderByExternalInvoiceID(ctx context.Context, externalInvoiceID pgtype.Text) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByExternalInvoiceID, externalInvoiceID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Gateway,
		&i.ExternalInvoiceID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.DurationMonths,
		&i.Metadata,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, plan_id, gateway, external_invoice_id, amount, currency, status, duration_months, metadata, paid_at, created_at, updated_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Gateway,
		&i.ExternalInvoiceID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.DurationMonths,
		&i.Metadata,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentGatewayByName = `-- name: GetPaymentGatewayByName :one
SELECT id, name, is_enabled, config_encrypted, created_at, updated_at FROM payment_gateways WHERE name = $1
`

func (q *Queries) GetPaymentGatewayByName(ctx context.Context, name string) (PaymentGateway, error) {
	row := q.db.QueryRow(ctx, getPaymentGatewayByName, name)
	var i PaymentGateway
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsEnabled,
		&i.ConfigEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromoCodeByCode = `-- name: GetPromoCodeByCode :one
SELECT id, code, discount_percent, discount_amount, bonus_days, bonus_bytes, max_uses, used_count, is_active, expires_at, created_at FROM promo_codes WHERE code = $1 AND is_active = true
`

func (q *Queries) GetPromoCodeByCode(ctx context.Context, code string) (PromoCode, error) {
	row := q.db.QueryRow(ctx, getPromoCodeByCode, code)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountPercent,
		&i.DiscountAmount,
		&i.BonusDays,
		&i.BonusBytes,
		&i.MaxUses,
		&i.UsedCount,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementPromoCodeUsage = `-- name: IncrementPromoCodeUsage :exec
UPDATE promo_codes SET used_count = used_count + 1 WHERE id = $1
`

func (q *Queries) IncrementPromoCodeUsage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementPromoCodeUsage, id)
	return err
}

const listBroadcastCampaigns = `-- name: ListBroadcastCampaigns :many
SELECT id, title, target_segment, message_text, inline_buttons, total_recipients, sent_count, failed_count, status, created_at, completed_at FROM broadcast_campaigns ORDER BY created_at DESC
`

func (q *Queries) ListBroadcastCampaigns(ctx context.Context) ([]BroadcastCampaign, error) {
	rows, err := q.db.Query(ctx, listBroadcastCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BroadcastCampaign{}
	for rows.Next() {
		var i BroadcastCampaign
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TargetSegment,
			&i.MessageText,
			&i.InlineButtons,
			&i.TotalRecipients,
			&i.SentCount,
			&i.FailedCount,
			&i.Status,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUserID = `-- name: ListOrdersByUserID :many
SELECT id, user_id, plan_id, gateway, external_invoice_id, amount, currency, status, duration_months, metadata, paid_at, created_at, updated_at FROM orders WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByUserID(ctx context.Context, userID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Gateway,
			&i.ExternalInvoiceID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.DurationMonths,
			&i.Metadata,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentGateways = `-- name: ListPaymentGateways :many
SELECT id, name, is_enabled, config_encrypted, created_at, updated_at FROM payment_gateways ORDER BY name
`

func (q *Queries) ListPaymentGateways(ctx context.Context) ([]PaymentGateway, error) {
	rows, err := q.db.Query(ctx, listPaymentGateways)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentGateway{}
	for rows.Next() {
		var i PaymentGateway
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsEnabled,
			&i.ConfigEncrypted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromoCodes = `-- name: ListPromoCodes :many
SELECT id, code, discount_percent, discount_amount, bonus_days, bonus_bytes, max_uses, used_count, is_active, expires_at, created_at FROM promo_codes ORDER BY created_at DESC
`

func (q *Queries) ListPromoCodes(ctx context.Context) ([]PromoCode, error) {
	rows, err := q.db.Query(ctx, listPromoCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromoCode{}
	for rows.Next() {
		var i PromoCode
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.DiscountPercent,
			&i.DiscountAmount,
			&i.BonusDays,
			&i.BonusBytes,
			&i.MaxUses,
			&i.UsedCount,
			&i.IsActive,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBroadcastCampaignStats = `-- name: UpdateBroadcastCampaignStats :one
UPDATE broadcast_campaigns
SET sent_count = $2, failed_count = $3, status = $4, completed_at = $5
WHERE id = $1
RETURNING id, title, target_segment, message_text, inline_buttons, total_recipients, sent_count, failed_count, status, created_at, completed_at
`

type UpdateBroadcastCampaignStatsParams struct {
	ID          uuid.UUID          `json:"id"`
	SentCount   pgtype.Int4        `json:"sent_count"`
	FailedCount pgtype.Int4        `json:"failed_count"`
	Status      pgtype.Text        `json:"status"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateBroadcastCampaignStats(ctx context.Context, arg UpdateBroadcastCampaignStatsParams) (BroadcastCampaign, error) {
	row := q.db.QueryRow(ctx, updateBroadcastCampaignStats,
		arg.ID,
		arg.SentCount,
		arg.FailedCount,
		arg.Status,
		arg.CompletedAt,
	)
	var i BroadcastCampaign
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TargetSegment,
		&i.MessageText,
		&i.InlineButtons,
		&i.TotalRecipients,
		&i.SentCount,
		&i.FailedCount,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2, paid_at = $3, updated_at = now()
WHERE id = $1
RETURNING id, user_id, plan_id, gateway, external_invoice_id, amount, currency, status, duration_months, metadata, paid_at, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID          `json:"id"`
	Status pgtype.Text        `json:"status"`
	PaidAt pgtype.Timestamptz `json:"paid_at"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status, arg.PaidAt)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Gateway,
		&i.ExternalInvoiceID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.DurationMonths,
		&i.Metadata,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBillingSettings = `-- name: UpsertBillingSettings :one
INSERT INTO billing_settings (id, cryptobot_api_token, cryptobot_enabled, telegram_stars_enabled, stars_price_per_month, webhook_secret, updated_at)
VALUES (1, $1, $2, $3, $4, $5, now())
ON CONFLICT (id) DO UPDATE
SET cryptobot_api_token = EXCLUDED.cryptobot_api_token,
    cryptobot_enabled = EXCLUDED.cryptobot_enabled,
    telegram_stars_enabled = EXCLUDED.telegram_stars_enabled,
    stars_price_per_month = EXCLUDED.stars_price_per_month,
    webhook_secret = EXCLUDED.webhook_secret,
    updated_at = now()
RETURNING cryptobot_api_token, cryptobot_enabled, telegram_stars_enabled, stars_price_per_month, webhook_secret, updated_at
`

type UpsertBillingSettingsParams struct {
	CryptobotApiToken    string `json:"cryptobot_api_token"`
	CryptobotEnabled     bool   `json:"cryptobot_enabled"`
	TelegramStarsEnabled bool   `json:"telegram_stars_enabled"`
	StarsPricePerMonth   int32  `json:"stars_price_per_month"`
	WebhookSecret        string `json:"webhook_secret"`
}

type UpsertBillingSettingsRow struct {
	CryptobotApiToken    string             `json:"cryptobot_api_token"`
	CryptobotEnabled     bool               `json:"cryptobot_enabled"`
	TelegramStarsEnabled bool               `json:"telegram_stars_enabled"`
	StarsPricePerMonth   int32              `json:"stars_price_per_month"`
	WebhookSecret        string             `json:"webhook_secret"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertBillingSettings(ctx context.Context, arg UpsertBillingSettingsParams) (UpsertBillingSettingsRow, error) {
	row := q.db.QueryRow(ctx, upsertBillingSettings,
		arg.CryptobotApiToken,
		arg.CryptobotEnabled,
		arg.TelegramStarsEnabled,
		arg.StarsPricePerMonth,
		arg.WebhookSecret,
	)
	var i UpsertBillingSettingsRow
	err := row.Scan(
		&i.CryptobotApiToken,
		&i.CryptobotEnabled,
		&i.TelegramStarsEnabled,
		&i.StarsPricePerMonth,
		&i.WebhookSecret,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPaymentGateway = `-- name: UpsertPaymentGateway :one
INSERT INTO payment_gateways (name, is_enabled, config_encrypted)
VALUES ($1, $2, $3)
ON CONFLICT (name) DO UPDATE
SET is_enabled = EXCLUDED.is_enabled, config_encrypted = EXCLUDED.config_encrypted, updated_at = now()
RETURNING id, name, is_enabled, config_encrypted, created_at, updated_at
`

type UpsertPaymentGatewayParams struct {
	Name            string      `json:"name"`
	IsEnabled       pgtype.Bool `json:"is_enabled"`
	ConfigEncrypted string      `json:"config_encrypted"`
}

func (q *Queries) UpsertPaymentGateway(ctx context.Context, arg UpsertPaymentGatewayParams) (PaymentGateway, error) {
	row := q.db.QueryRow(ctx, upsertPaymentGateway, arg.Name, arg.IsEnabled, arg.ConfigEncrypted)
	var i PaymentGateway
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsEnabled,
		&i.ConfigEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
