// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"net"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         pgtype.Text        `json:"role"`
	TotpSecret   pgtype.Text        `json:"totp_secret"`
	LastLogin    pgtype.Timestamptz `json:"last_login"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ApiKey struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	KeyHash    string             `json:"key_hash"`
	Prefix     string             `json:"prefix"`
	Scopes     []string           `json:"scopes"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID           int64              `json:"id"`
	AdminID      pgtype.UUID        `json:"admin_id"`
	ApiKeyID     pgtype.UUID        `json:"api_key_id"`
	Action       string             `json:"action"`
	ResourceType pgtype.Text        `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	Diff         []byte             `json:"diff"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type BillingSetting struct {
	ID                   int32              `json:"id"`
	CryptobotApiToken    string             `json:"cryptobot_api_token"`
	CryptobotEnabled     bool               `json:"cryptobot_enabled"`
	TelegramStarsEnabled bool               `json:"telegram_stars_enabled"`
	StarsPricePerMonth   int32              `json:"stars_price_per_month"`
	WebhookSecret        string             `json:"webhook_secret"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type BroadcastCampaign struct {
	ID              uuid.UUID          `json:"id"`
	Title           string             `json:"title"`
	TargetSegment   string             `json:"target_segment"`
	MessageText     string             `json:"message_text"`
	InlineButtons   []byte             `json:"inline_buttons"`
	TotalRecipients pgtype.Int4        `json:"total_recipients"`
	SentCount       pgtype.Int4        `json:"sent_count"`
	FailedCount     pgtype.Int4        `json:"failed_count"`
	Status          pgtype.Text        `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

type Credential struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	NodeID       uuid.UUID          `json:"node_id"`
	Protocol     string             `json:"protocol"`
	PrivateKey   pgtype.Text        `json:"private_key"`
	PublicKey    pgtype.Text        `json:"public_key"`
	PresharedKey pgtype.Text        `json:"preshared_key"`
	Uuid         pgtype.UUID        `json:"uuid"`
	Password     pgtype.Text        `json:"password"`
	Email        pgtype.Text        `json:"email"`
	Flow         pgtype.Text        `json:"flow"`
	Ipv4         *netip.Addr        `json:"ipv4"`
	Ipv6         *netip.Addr        `json:"ipv6"`
	Dns          pgtype.Text        `json:"dns"`
	Mtu          pgtype.Int4        `json:"mtu"`
	Keepalive    pgtype.Int4        `json:"keepalive"`
	AllowedIps   []net.IPNet        `json:"allowed_ips"`
	Status       pgtype.Text        `json:"status"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	AwgJc        pgtype.Int4        `json:"awg_jc"`
	AwgJmin      pgtype.Int4        `json:"awg_jmin"`
	AwgJmax      pgtype.Int4        `json:"awg_jmax"`
	AwgS1        pgtype.Int4        `json:"awg_s1"`
	AwgS2        pgtype.Int4        `json:"awg_s2"`
	AwgH1        pgtype.Int8        `json:"awg_h1"`
	AwgH2        pgtype.Int8        `json:"awg_h2"`
	AwgH3        pgtype.Int8        `json:"awg_h3"`
	AwgH4        pgtype.Int8        `json:"awg_h4"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Node struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Endpoint        string             `json:"endpoint"`
	GrpcEndpoint    string             `json:"grpc_endpoint"`
	Region          pgtype.Text        `json:"region"`
	CapacityGbps    pgtype.Int4        `json:"capacity_gbps"`
	Status          pgtype.Text        `json:"status"`
	Tags            []byte             `json:"tags"`
	PublicKey       string             `json:"public_key"`
	CertFingerprint string             `json:"cert_fingerprint"`
	LastHeartbeat   pgtype.Timestamptz `json:"last_heartbeat"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	PlanID            uuid.UUID          `json:"plan_id"`
	Gateway           string             `json:"gateway"`
	ExternalInvoiceID pgtype.Text        `json:"external_invoice_id"`
	Amount            pgtype.Numeric     `json:"amount"`
	Currency          string             `json:"currency"`
	Status            pgtype.Text        `json:"status"`
	DurationMonths    pgtype.Int4        `json:"duration_months"`
	Metadata          []byte             `json:"metadata"`
	PaidAt            pgtype.Timestamptz `json:"paid_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type PaymentGateway struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	IsEnabled       pgtype.Bool        `json:"is_enabled"`
	ConfigEncrypted string             `json:"config_encrypted"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Plan struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	MonthlyPrice       pgtype.Numeric     `json:"monthly_price"`
	TrafficLimit       pgtype.Int8        `json:"traffic_limit"`
	DeviceLimit        pgtype.Int4        `json:"device_limit"`
	Protocols          []string           `json:"protocols"`
	Features           []byte             `json:"features"`
	IsActive           pgtype.Bool        `json:"is_active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	IsTrial            pgtype.Bool        `json:"is_trial"`
	TrialDurationHours pgtype.Int4        `json:"trial_duration_hours"`
	PriceStars         pgtype.Int4        `json:"price_stars"`
	MaxDevices         pgtype.Int4        `json:"max_devices"`
	TrafficLimitGb     pgtype.Int4        `json:"traffic_limit_gb"`
	Price1m            pgtype.Numeric     `json:"price_1m"`
	Price3m            pgtype.Numeric     `json:"price_3m"`
	Price6m            pgtype.Numeric     `json:"price_6m"`
	Price12m           pgtype.Numeric     `json:"price_12m"`
}

type PromoCode struct {
	ID              uuid.UUID          `json:"id"`
	Code            string             `json:"code"`
	DiscountPercent pgtype.Int4        `json:"discount_percent"`
	DiscountAmount  pgtype.Numeric     `json:"discount_amount"`
	BonusDays       pgtype.Int4        `json:"bonus_days"`
	BonusBytes      pgtype.Int8        `json:"bonus_bytes"`
	MaxUses         pgtype.Int4        `json:"max_uses"`
	UsedCount       pgtype.Int4        `json:"used_count"`
	IsActive        pgtype.Bool        `json:"is_active"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type TrafficStat struct {
	ID         int64              `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	NodeID     uuid.UUID          `json:"node_id"`
	Protocol   string             `json:"protocol"`
	HourBucket time.Time          `json:"hour_bucket"`
	RxBytes    pgtype.Int8        `json:"rx_bytes"`
	TxBytes    pgtype.Int8        `json:"tx_bytes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                uuid.UUID          `json:"id"`
	Email             pgtype.Text        `json:"email"`
	Username          string             `json:"username"`
	PasswordHash      pgtype.Text        `json:"password_hash"`
	Status            pgtype.Text        `json:"status"`
	PlanID            pgtype.UUID        `json:"plan_id"`
	TrafficLimit      pgtype.Int8        `json:"traffic_limit"`
	TrafficUsed       pgtype.Int8        `json:"traffic_used"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	SubscriptionToken uuid.UUID          `json:"subscription_token"`
	Note              pgtype.Text        `json:"note"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	TelegramID        pgtype.Int8        `json:"telegram_id"`
	TelegramUsername  pgtype.Text        `json:"telegram_username"`
	TrialUsed         pgtype.Bool        `json:"trial_used"`
	ReferrerID        pgtype.UUID        `json:"referrer_id"`
	ReferralCode      pgtype.Text        `json:"referral_code"`
	IsBanned          pgtype.Bool        `json:"is_banned"`
	BanReason         pgtype.Text        `json:"ban_reason"`
}

type Webhook struct {
	ID        uuid.UUID          `json:"id"`
	Url       string             `json:"url"`
	Secret    string             `json:"secret"`
	Events    []string           `json:"events"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
