// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: node.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countNodes = `-- name: CountNodes :one
SELECT COUNT(*) FROM nodes
WHERE ($1 = '' OR status = $1)
AND ($2 = '' OR region = $2)
`

type CountNodesParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) CountNodes(ctx context.Context, arg CountNodesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNodes, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (name, endpoint, grpc_endpoint, region, capacity_gbps, status, tags, public_key, cert_fingerprint)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, endpoint, grpc_endpoint, region, capacity_gbps, status, tags, public_key, cert_fingerprint, reality_sni, reality_pbk, reality_sid, last_heartbeat, created_at, updated_at
`

type CreateNodeParams struct {
	Name            string      `json:"name"`
	Endpoint        string      `json:"endpoint"`
	GrpcEndpoint    string      `json:"grpc_endpoint"`
	Region          pgtype.Text `json:"region"`
	CapacityGbps    pgtype.Int4 `json:"capacity_gbps"`
	Status          pgtype.Text `json:"status"`
	Tags            []byte      `json:"tags"`
	PublicKey       string      `json:"public_key"`
	CertFingerprint string      `json:"cert_fingerprint"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.Name,
		arg.Endpoint,
		arg.GrpcEndpoint,
		arg.Region,
		arg.CapacityGbps,
		arg.Status,
		arg.Tags,
		arg.PublicKey,
		arg.CertFingerprint,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.GrpcEndpoint,
		&i.Region,
		&i.CapacityGbps,
		&i.Status,
		&i.Tags,
		&i.PublicKey,
		&i.CertFingerprint,
		&i.RealitySni,
		&i.RealityPbk,
		&i.RealitySid,
		&i.LastHeartbeat,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE id = $1
`

func (q *Queries) DeleteNode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNode, id)
	return err
}

const getNodeByID = `-- name: GetNodeByID :one
SELECT id, name, endpoint, grpc_endpoint, region, capacity_gbps, status, tags, public_key, cert_fingerprint, reality_sni, reality_pbk, reality_sid, last_heartbeat, created_at, updated_at FROM nodes WHERE id = $1
`

func (q *Queries) GetNodeByID(ctx context.Context, id uuid.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByID, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.GrpcEndpoint,
		&i.Region,
		&i.CapacityGbps,
		&i.Status,
		&i.Tags,
		&i.PublicKey,
		&i.CertFingerprint,
		&i.RealitySni,
		&i.RealityPbk,
		&i.RealitySid,
		&i.LastHeartbeat,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNodeByName = `-- name: GetNodeByName :one
SELECT id, name, endpoint, grpc_endpoint, region, capacity_gbps, status, tags, public_key, cert_fingerprint, reality_sni, reality_pbk, reality_sid, last_heartbeat, created_at, updated_at FROM nodes WHERE name = $1
`

func (q *Queries) GetNodeByName(ctx context.Context, name string) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByName, name)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.GrpcEndpoint,
		&i.Region,
		&i.CapacityGbps,
		&i.Status,
		&i.Tags,
		&i.PublicKey,
		&i.CertFingerprint,
		&i.RealitySni,
		&i.RealityPbk,
		&i.RealitySid,
		&i.LastHeartbeat,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveNodes = `-- name: ListActiveNodes :many
SELECT id, name, endpoint, grpc_endpoint, region, capacity_gbps, status, tags, public_key, cert_fingerprint, reality_sni, reality_pbk, reality_sid, last_heartbeat, created_at, updated_at FROM nodes WHERE status = 'online' ORDER BY name
`

func (q *Queries) ListActiveNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, listActiveNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Endpoint,
			&i.GrpcEndpoint,
			&i.Region,
			&i.CapacityGbps,
			&i.Status,
			&i.Tags,
			&i.PublicKey,
			&i.CertFingerprint,
			&i.RealitySni,
			&i.RealityPbk,
			&i.RealitySid,
			&i.LastHeartbeat,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodes = `-- name: ListNodes :many
SELECT id, name, endpoint, grpc_endpoint, region, capacity_gbps, status, tags, public_key, cert_fingerprint, reality_sni, reality_pbk, reality_sid, last_heartbeat, created_at, updated_at FROM nodes
WHERE ($1 = '' OR status = $1)
AND ($2 = '' OR region = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListNodesParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListNodes(ctx context.Context, arg ListNodesParams) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodes,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Endpoint,
			&i.GrpcEndpoint,
			&i.Region,
			&i.CapacityGbps,
			&i.Status,
			&i.Tags,
			&i.PublicKey,
			&i.CertFingerprint,
			&i.RealitySni,
			&i.RealityPbk,
			&i.RealitySid,
			&i.LastHeartbeat,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNode = `-- name: UpdateNode :one
UPDATE nodes
SET name = $2, endpoint = $3, grpc_endpoint = $4, region = $5, capacity_gbps = $6, status = $7, tags = $8, public_key = $9, cert_fingerprint = $10, reality_sni = $11, reality_pbk = $12, reality_sid = $13, updated_at = now()
WHERE id = $1
RETURNING id, name, endpoint, grpc_endpoint, region, capacity_gbps, status, tags, public_key, cert_fingerprint, reality_sni, reality_pbk, reality_sid, last_heartbeat, created_at, updated_at
`

type UpdateNodeParams struct {
	ID              uuid.UUID   `json:"id"`
	Name            string      `json:"name"`
	Endpoint        string      `json:"endpoint"`
	GrpcEndpoint    string      `json:"grpc_endpoint"`
	Region          pgtype.Text `json:"region"`
	CapacityGbps    pgtype.Int4 `json:"capacity_gbps"`
	Status          pgtype.Text `json:"status"`
	Tags            []byte      `json:"tags"`
	PublicKey       string      `json:"public_key"`
	CertFingerprint string      `json:"cert_fingerprint"`
	RealitySni      pgtype.Text `json:"reality_sni"`
	RealityPbk      pgtype.Text `json:"reality_pbk"`
	RealitySid      pgtype.Text `json:"reality_sid"`
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNode,
		arg.ID,
		arg.Name,
		arg.Endpoint,
		arg.GrpcEndpoint,
		arg.Region,
		arg.CapacityGbps,
		arg.Status,
		arg.Tags,
		arg.PublicKey,
		arg.CertFingerprint,
		arg.RealitySni,
		arg.RealityPbk,
		arg.RealitySid,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.GrpcEndpoint,
		&i.Region,
		&i.CapacityGbps,
		&i.Status,
		&i.Tags,
		&i.PublicKey,
		&i.CertFingerprint,
		&i.RealitySni,
		&i.RealityPbk,
		&i.RealitySid,
		&i.LastHeartbeat,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNodeHeartbeat = `-- name: UpdateNodeHeartbeat :exec
UPDATE nodes SET last_heartbeat = now(), status = $2, updated_at = now() WHERE id = $1
`

type UpdateNodeHeartbeatParams struct {
	ID     uuid.UUID   `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateNodeHeartbeat(ctx context.Context, arg UpdateNodeHeartbeatParams) error {
	_, err := q.db.Exec(ctx, updateNodeHeartbeat, arg.ID, arg.Status)
	return err
}
