// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plan.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (name, monthly_price, traffic_limit, device_limit, protocols, features, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, monthly_price, traffic_limit, device_limit, protocols, features, is_active, created_at
`

type CreatePlanParams struct {
	Name         string         `json:"name"`
	MonthlyPrice pgtype.Numeric `json:"monthly_price"`
	TrafficLimit pgtype.Int8    `json:"traffic_limit"`
	DeviceLimit  pgtype.Int4    `json:"device_limit"`
	Protocols    []string       `json:"protocols"`
	Features     []byte         `json:"features"`
	IsActive     pgtype.Bool    `json:"is_active"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.Name,
		arg.MonthlyPrice,
		arg.TrafficLimit,
		arg.DeviceLimit,
		arg.Protocols,
		arg.Features,
		arg.IsActive,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MonthlyPrice,
		&i.TrafficLimit,
		&i.DeviceLimit,
		&i.Protocols,
		&i.Features,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plans WHERE id = $1
`

func (q *Queries) DeletePlan(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlan, id)
	return err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, name, monthly_price, traffic_limit, device_limit, protocols, features, is_active, created_at FROM plans WHERE id = $1
`

func (q *Queries) GetPlanByID(ctx context.Context, id uuid.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MonthlyPrice,
		&i.TrafficLimit,
		&i.DeviceLimit,
		&i.Protocols,
		&i.Features,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanByName = `-- name: GetPlanByName :one
SELECT id, name, monthly_price, traffic_limit, device_limit, protocols, features, is_active, created_at FROM plans WHERE name = $1
`

func (q *Queries) GetPlanByName(ctx context.Context, name string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByName, name)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MonthlyPrice,
		&i.TrafficLimit,
		&i.DeviceLimit,
		&i.Protocols,
		&i.Features,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT id, name, monthly_price, traffic_limit, device_limit, protocols, features, is_active, created_at FROM plans WHERE is_active = true ORDER BY name
`

func (q *Queries) ListPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MonthlyPrice,
			&i.TrafficLimit,
			&i.DeviceLimit,
			&i.Protocols,
			&i.Features,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE plans
SET name = $2, monthly_price = $3, traffic_limit = $4, device_limit = $5, protocols = $6, features = $7, is_active = $8, updated_at = now()
WHERE id = $1
RETURNING id, name, monthly_price, traffic_limit, device_limit, protocols, features, is_active, created_at
`

type UpdatePlanParams struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	MonthlyPrice pgtype.Numeric `json:"monthly_price"`
	TrafficLimit pgtype.Int8    `json:"traffic_limit"`
	DeviceLimit  pgtype.Int4    `json:"device_limit"`
	Protocols    []string       `json:"protocols"`
	Features     []byte         `json:"features"`
	IsActive     pgtype.Bool    `json:"is_active"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.ID,
		arg.Name,
		arg.MonthlyPrice,
		arg.TrafficLimit,
		arg.DeviceLimit,
		arg.Protocols,
		arg.Features,
		arg.IsActive,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MonthlyPrice,
		&i.TrafficLimit,
		&i.DeviceLimit,
		&i.Protocols,
		&i.Features,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
