// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error)
	CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error)
	CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAPIKey(ctx context.Context, id uuid.UUID) error
	DeleteAdmin(ctx context.Context, id uuid.UUID) error
	DeleteCredential(ctx context.Context, id uuid.UUID) error
	DeleteNode(ctx context.Context, id uuid.UUID) error
	DeletePlan(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetAPIKeyByPrefix(ctx context.Context, prefix string) (ApiKey, error)
	GetAdminByEmail(ctx context.Context, email string) (Admin, error)
	GetAdminByID(ctx context.Context, id uuid.UUID) (Admin, error)
	GetCredentialByID(ctx context.Context, id uuid.UUID) (Credential, error)
	GetCredentialByUserNodeProtocol(ctx context.Context, arg GetCredentialByUserNodeProtocolParams) (Credential, error)
	GetNodeByID(ctx context.Context, id uuid.UUID) (Node, error)
	GetNodeByName(ctx context.Context, name string) (Node, error)
	GetPlanByID(ctx context.Context, id uuid.UUID) (Plan, error)
	GetPlanByName(ctx context.Context, name string) (Plan, error)
	GetTrafficAggregateByNode(ctx context.Context, arg GetTrafficAggregateByNodeParams) ([]GetTrafficAggregateByNodeRow, error)
	GetTrafficAggregateByUser(ctx context.Context, arg GetTrafficAggregateByUserParams) (GetTrafficAggregateByUserRow, error)
	GetTrafficStatsByUserHour(ctx context.Context, arg GetTrafficStatsByUserHourParams) (TrafficStat, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListAPIKeys(ctx context.Context) ([]ApiKey, error)
	ListAdmins(ctx context.Context) ([]Admin, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListCredentialsByNode(ctx context.Context, nodeID uuid.UUID) ([]Credential, error)
	ListCredentialsByUser(ctx context.Context, userID uuid.UUID) ([]Credential, error)
	ListNodes(ctx context.Context, arg ListNodesParams) ([]Node, error)
	ListPlans(ctx context.Context) ([]Plan, error)
	ListTrafficStatsByUser(ctx context.Context, arg ListTrafficStatsByUserParams) ([]TrafficStat, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ResetUserTraffic(ctx context.Context, id uuid.UUID) error
	UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) (ApiKey, error)
	UpdateAdmin(ctx context.Context, arg UpdateAdminParams) (Admin, error)
	UpdateAdminLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateCredential(ctx context.Context, arg UpdateCredentialParams) (Credential, error)
	UpdateNode(ctx context.Context, arg UpdateNodeParams) (Node, error)
	UpdateNodeHeartbeat(ctx context.Context, arg UpdateNodeHeartbeatParams) error
	UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserTraffic(ctx context.Context, arg UpdateUserTrafficParams) error
	UpsertTrafficStats(ctx context.Context, arg UpsertTrafficStatsParams) (TrafficStat, error)
}

var _ Querier = (*Queries)(nil)
