// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: traffic.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getTrafficAggregateByNode = `-- name: GetTrafficAggregateByNode :many
SELECT
    node_id,
    protocol,
    COALESCE(SUM(rx_bytes), 0)::bigint as total_rx,
    COALESCE(SUM(tx_bytes), 0)::bigint as total_tx
FROM traffic_stats
WHERE hour_bucket >= $1 AND hour_bucket <= $2
GROUP BY node_id, protocol
`

type GetTrafficAggregateByNodeParams struct {
	HourBucket   time.Time `json:"hour_bucket"`
	HourBucket_2 time.Time `json:"hour_bucket_2"`
}

type GetTrafficAggregateByNodeRow struct {
	NodeID   uuid.UUID `json:"node_id"`
	Protocol string    `json:"protocol"`
	TotalRx  int64     `json:"total_rx"`
	TotalTx  int64     `json:"total_tx"`
}

func (q *Queries) GetTrafficAggregateByNode(ctx context.Context, arg GetTrafficAggregateByNodeParams) ([]GetTrafficAggregateByNodeRow, error) {
	rows, err := q.db.Query(ctx, getTrafficAggregateByNode, arg.HourBucket, arg.HourBucket_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTrafficAggregateByNodeRow{}
	for rows.Next() {
		var i GetTrafficAggregateByNodeRow
		if err := rows.Scan(
			&i.NodeID,
			&i.Protocol,
			&i.TotalRx,
			&i.TotalTx,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrafficAggregateByUser = `-- name: GetTrafficAggregateByUser :one
SELECT
    COALESCE(SUM(rx_bytes), 0)::bigint as total_rx,
    COALESCE(SUM(tx_bytes), 0)::bigint as total_tx
FROM traffic_stats
WHERE user_id = $1 AND hour_bucket >= $2 AND hour_bucket <= $3
`

type GetTrafficAggregateByUserParams struct {
	UserID       uuid.UUID `json:"user_id"`
	HourBucket   time.Time `json:"hour_bucket"`
	HourBucket_2 time.Time `json:"hour_bucket_2"`
}

type GetTrafficAggregateByUserRow struct {
	TotalRx int64 `json:"total_rx"`
	TotalTx int64 `json:"total_tx"`
}

func (q *Queries) GetTrafficAggregateByUser(ctx context.Context, arg GetTrafficAggregateByUserParams) (GetTrafficAggregateByUserRow, error) {
	row := q.db.QueryRow(ctx, getTrafficAggregateByUser, arg.UserID, arg.HourBucket, arg.HourBucket_2)
	var i GetTrafficAggregateByUserRow
	err := row.Scan(&i.TotalRx, &i.TotalTx)
	return i, err
}

const getTrafficStatsByUserHour = `-- name: GetTrafficStatsByUserHour :one
SELECT id, user_id, node_id, protocol, hour_bucket, rx_bytes, tx_bytes, created_at FROM traffic_stats WHERE user_id = $1 AND node_id = $2 AND protocol = $3 AND hour_bucket = $4
`

type GetTrafficStatsByUserHourParams struct {
	UserID     uuid.UUID `json:"user_id"`
	NodeID     uuid.UUID `json:"node_id"`
	Protocol   string    `json:"protocol"`
	HourBucket time.Time `json:"hour_bucket"`
}

func (q *Queries) GetTrafficStatsByUserHour(ctx context.Context, arg GetTrafficStatsByUserHourParams) (TrafficStat, error) {
	row := q.db.QueryRow(ctx, getTrafficStatsByUserHour,
		arg.UserID,
		arg.NodeID,
		arg.Protocol,
		arg.HourBucket,
	)
	var i TrafficStat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NodeID,
		&i.Protocol,
		&i.HourBucket,
		&i.RxBytes,
		&i.TxBytes,
		&i.CreatedAt,
	)
	return i, err
}

const listTrafficStatsByUser = `-- name: ListTrafficStatsByUser :many
SELECT id, user_id, node_id, protocol, hour_bucket, rx_bytes, tx_bytes, created_at FROM traffic_stats
WHERE user_id = $1
AND hour_bucket >= $2 AND hour_bucket <= $3
ORDER BY hour_bucket DESC
`

type ListTrafficStatsByUserParams struct {
	UserID       uuid.UUID `json:"user_id"`
	HourBucket   time.Time `json:"hour_bucket"`
	HourBucket_2 time.Time `json:"hour_bucket_2"`
}

func (q *Queries) ListTrafficStatsByUser(ctx context.Context, arg ListTrafficStatsByUserParams) ([]TrafficStat, error) {
	rows, err := q.db.Query(ctx, listTrafficStatsByUser, arg.UserID, arg.HourBucket, arg.HourBucket_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrafficStat{}
	for rows.Next() {
		var i TrafficStat
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NodeID,
			&i.Protocol,
			&i.HourBucket,
			&i.RxBytes,
			&i.TxBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTrafficStats = `-- name: UpsertTrafficStats :one
INSERT INTO traffic_stats (user_id, node_id, protocol, hour_bucket, rx_bytes, tx_bytes)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, node_id, protocol, hour_bucket) DO UPDATE SET
    rx_bytes = traffic_stats.rx_bytes + EXCLUDED.rx_bytes,
    tx_bytes = traffic_stats.tx_bytes + EXCLUDED.tx_bytes,
    created_at = now()
RETURNING id, user_id, node_id, protocol, hour_bucket, rx_bytes, tx_bytes, created_at
`

type UpsertTrafficStatsParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	NodeID     uuid.UUID   `json:"node_id"`
	Protocol   string      `json:"protocol"`
	HourBucket time.Time   `json:"hour_bucket"`
	RxBytes    pgtype.Int8 `json:"rx_bytes"`
	TxBytes    pgtype.Int8 `json:"tx_bytes"`
}

func (q *Queries) UpsertTrafficStats(ctx context.Context, arg UpsertTrafficStatsParams) (TrafficStat, error) {
	row := q.db.QueryRow(ctx, upsertTrafficStats,
		arg.UserID,
		arg.NodeID,
		arg.Protocol,
		arg.HourBucket,
		arg.RxBytes,
		arg.TxBytes,
	)
	var i TrafficStat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NodeID,
		&i.Protocol,
		&i.HourBucket,
		&i.RxBytes,
		&i.TxBytes,
		&i.CreatedAt,
	)
	return i, err
}
