// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE ($1 = '' OR status = $1)
AND ($2::uuid IS NULL OR $2::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR plan_id = $2)
`

type CountUsersParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 uuid.UUID   `json:"column_2"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username, password_hash, status, plan_id, traffic_limit, traffic_used, expires_at, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, email, username, password_hash, status, plan_id, traffic_limit, traffic_used, expires_at, subscription_token, note, created_at, updated_at
`

type CreateUserParams struct {
	Email        pgtype.Text        `json:"email"`
	Username     string             `json:"username"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	Status       pgtype.Text        `json:"status"`
	PlanID       pgtype.UUID        `json:"plan_id"`
	TrafficLimit pgtype.Int8        `json:"traffic_limit"`
	TrafficUsed  pgtype.Int8        `json:"traffic_used"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	Note         pgtype.Text        `json:"note"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.Status,
		arg.PlanID,
		arg.TrafficLimit,
		arg.TrafficUsed,
		arg.ExpiresAt,
		arg.Note,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Status,
		&i.PlanID,
		&i.TrafficLimit,
		&i.TrafficUsed,
		&i.ExpiresAt,
		&i.SubscriptionToken,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password_hash, status, plan_id, traffic_limit, traffic_used, expires_at, subscription_token, note, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Status,
		&i.PlanID,
		&i.TrafficLimit,
		&i.TrafficUsed,
		&i.ExpiresAt,
		&i.SubscriptionToken,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, password_hash, status, plan_id, traffic_limit, traffic_used, expires_at, subscription_token, note, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Status,
		&i.PlanID,
		&i.TrafficLimit,
		&i.TrafficUsed,
		&i.ExpiresAt,
		&i.SubscriptionToken,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBySubscriptionToken = `-- name: GetUserBySubscriptionToken :one
SELECT id, email, username, password_hash, status, plan_id, traffic_limit, traffic_used, expires_at, subscription_token, note, created_at, updated_at FROM users WHERE subscription_token = $1
`

func (q *Queries) GetUserBySubscriptionToken(ctx context.Context, subscriptionToken uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySubscriptionToken, subscriptionToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Status,
		&i.PlanID,
		&i.TrafficLimit,
		&i.TrafficUsed,
		&i.ExpiresAt,
		&i.SubscriptionToken,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, password_hash, status, plan_id, traffic_limit, traffic_used, expires_at, subscription_token, note, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Status,
		&i.PlanID,
		&i.TrafficLimit,
		&i.TrafficUsed,
		&i.ExpiresAt,
		&i.SubscriptionToken,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, username, password_hash, status, plan_id, traffic_limit, traffic_used, expires_at, subscription_token, note, created_at, updated_at FROM users
WHERE ($1 = '' OR status = $1)
AND ($2::uuid IS NULL OR $2::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR plan_id = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListUsersParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 uuid.UUID   `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.Status,
			&i.PlanID,
			&i.TrafficLimit,
			&i.TrafficUsed,
			&i.ExpiresAt,
			&i.SubscriptionToken,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetUserTraffic = `-- name: ResetUserTraffic :exec
UPDATE users SET traffic_used = 0, updated_at = now() WHERE id = $1
`

func (q *Queries) ResetUserTraffic(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetUserTraffic, id)
	return err
}

const rotateUserSubscriptionToken = `-- name: RotateUserSubscriptionToken :one
UPDATE users SET subscription_token = gen_random_uuid(), updated_at = now() WHERE id = $1 RETURNING id, email, username, password_hash, status, plan_id, traffic_limit, traffic_used, expires_at, subscription_token, note, created_at, updated_at
`

func (q *Queries) RotateUserSubscriptionToken(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, rotateUserSubscriptionToken, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Status,
		&i.PlanID,
		&i.TrafficLimit,
		&i.TrafficUsed,
		&i.ExpiresAt,
		&i.SubscriptionToken,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2, username = $3, password_hash = $4, status = $5, plan_id = $6, traffic_limit = $7, expires_at = $8, note = $9, updated_at = now()
WHERE id = $1
RETURNING id, email, username, password_hash, status, plan_id, traffic_limit, traffic_used, expires_at, subscription_token, note, created_at, updated_at
`

type UpdateUserParams struct {
	ID           uuid.UUID          `json:"id"`
	Email        pgtype.Text        `json:"email"`
	Username     string             `json:"username"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	Status       pgtype.Text        `json:"status"`
	PlanID       pgtype.UUID        `json:"plan_id"`
	TrafficLimit pgtype.Int8        `json:"traffic_limit"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	Note         pgtype.Text        `json:"note"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.Status,
		arg.PlanID,
		arg.TrafficLimit,
		arg.ExpiresAt,
		arg.Note,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Status,
		&i.PlanID,
		&i.TrafficLimit,
		&i.TrafficUsed,
		&i.ExpiresAt,
		&i.SubscriptionToken,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserTraffic = `-- name: UpdateUserTraffic :exec
UPDATE users SET traffic_used = traffic_used + $2, updated_at = now() WHERE id = $1
`

type UpdateUserTrafficParams struct {
	ID          uuid.UUID   `json:"id"`
	TrafficUsed pgtype.Int8 `json:"traffic_used"`
}

func (q *Queries) UpdateUserTraffic(ctx context.Context, arg UpdateUserTrafficParams) error {
	_, err := q.db.Exec(ctx, updateUserTraffic, arg.ID, arg.TrafficUsed)
	return err
}
