// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE ($1 = '' OR status = $1)
AND ($2::uuid IS NULL OR $2::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR plan_id = $2)
`

type CountUsersParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 uuid.UUID   `json:"column_2"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username, password_hash, status, plan_id, traffic_limit, traffic_used, expires_at, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, email, username, password_hash, status, plan_id, traffic_limit, traffic_used, expires_at, subscription_token, note, created_at, updated_at, telegram_id, telegram_username, trial_used, referrer_id, referral_code, is_banned, ban_reason
`

type CreateUserParams struct {
	Email        pgtype.Text        `json:"email"`
	Username     string             `json:"username"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	Status       pgtype.Text        `json:"status"`
	PlanID       pgtype.UUID        `json:"plan_id"`
	TrafficLimit pgtype.Int8        `json:"traffic_limit"`
	TrafficUsed  pgtype.Int8        `json:"traffic_used"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	Note         pgtype.Text        `json:"note"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.Status,
		arg.PlanID,
		arg.TrafficLimit,
		arg.TrafficUsed,
		arg.ExpiresAt,
		arg.Note,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Status,
		&i.PlanID,
		&i.TrafficLimit,
		&i.TrafficUsed,
		&i.ExpiresAt,
		&i.SubscriptionToken,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.TrialUsed,
		&i.ReferrerID,
		&i.ReferralCode,
		&i.IsBanned,
		&i.BanReason,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const extendUserSubscription = `-- name: ExtendUserSubscription :one
UPDATE users
SET expires_at = $2, traffic_limit = traffic_limit + $3, updated_at = now()
WHERE id = $1
RETURNING id, email, username, password_hash, status, plan_id, traffic_limit, traffic_used, expires_at, subscription_token, note, created_at, updated_at, telegram_id, telegram_username, trial_used, referrer_id, referral_code, is_banned, ban_reason
`

type ExtendUserSubscriptionParams struct {
	ID           uuid.UUID          `json:"id"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	TrafficLimit pgtype.Int8        `json:"traffic_limit"`
}

func (q *Queries) ExtendUserSubscription(ctx context.Context, arg ExtendUserSubscriptionParams) (User, error) {
	row := q.db.QueryRow(ctx, extendUserSubscription, arg.ID, arg.ExpiresAt, arg.TrafficLimit)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Status,
		&i.PlanID,
		&i.TrafficLimit,
		&i.TrafficUsed,
		&i.ExpiresAt,
		&i.SubscriptionToken,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.TrialUsed,
		&i.ReferrerID,
		&i.ReferralCode,
		&i.IsBanned,
		&i.BanReason,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password_hash, status, plan_id, traffic_limit, traffic_used, expires_at, subscription_token, note, created_at, updated_at, telegram_id, telegram_username, trial_used, referrer_id, referral_code, is_banned, ban_reason FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Status,
		&i.PlanID,
		&i.TrafficLimit,
		&i.TrafficUsed,
		&i.ExpiresAt,
		&i.SubscriptionToken,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.TrialUsed,
		&i.ReferrerID,
		&i.ReferralCode,
		&i.IsBanned,
		&i.BanReason,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, password_hash, status, plan_id, traffic_limit, traffic_used, expires_at, subscription_token, note, created_at, updated_at, telegram_id, telegram_username, trial_used, referrer_id, referral_code, is_banned, ban_reason FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Status,
		&i.PlanID,
		&i.TrafficLimit,
		&i.TrafficUsed,
		&i.ExpiresAt,
		&i.SubscriptionToken,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.TrialUsed,
		&i.ReferrerID,
		&i.ReferralCode,
		&i.IsBanned,
		&i.BanReason,
	)
	return i, err
}

const getUserByReferralCode = `-- name: GetUserByReferralCode :one
SELECT id, email, username, password_hash, status, plan_id, traffic_limit, traffic_used, expires_at, subscription_token, note, created_at, updated_at, telegram_id, telegram_username, trial_used, referrer_id, referral_code, is_banned, ban_reason FROM users WHERE referral_code = $1
`

func (q *Queries) GetUserByReferralCode(ctx context.Context, referralCode pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByReferralCode, referralCode)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Status,
		&i.PlanID,
		&i.TrafficLimit,
		&i.TrafficUsed,
		&i.ExpiresAt,
		&i.SubscriptionToken,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.TrialUsed,
		&i.ReferrerID,
		&i.ReferralCode,
		&i.IsBanned,
		&i.BanReason,
	)
	return i, err
}

const getUserBySubscriptionToken = `-- name: GetUserBySubscriptionToken :one
SELECT id, email, username, password_hash, status, plan_id, traffic_limit, traffic_used, expires_at, subscription_token, note, created_at, updated_at, telegram_id, telegram_username, trial_used, referrer_id, referral_code, is_banned, ban_reason FROM users WHERE subscription_token = $1
`

func (q *Queries) GetUserBySubscriptionToken(ctx context.Context, subscriptionToken uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySubscriptionToken, subscriptionToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Status,
		&i.PlanID,
		&i.TrafficLimit,
		&i.TrafficUsed,
		&i.ExpiresAt,
		&i.SubscriptionToken,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.TrialUsed,
		&i.ReferrerID,
		&i.ReferralCode,
		&i.IsBanned,
		&i.BanReason,
	)
	return i, err
}

const getUserByTelegramID = `-- name: GetUserByTelegramID :one
SELECT id, email, username, password_hash, status, plan_id, traffic_limit, traffic_used, expires_at, subscription_token, note, created_at, updated_at, telegram_id, telegram_username, trial_used, referrer_id, referral_code, is_banned, ban_reason FROM users WHERE telegram_id = $1
`

func (q *Queries) GetUserByTelegramID(ctx context.Context, telegramID pgtype.Int8) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramID, telegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Status,
		&i.PlanID,
		&i.TrafficLimit,
		&i.TrafficUsed,
		&i.ExpiresAt,
		&i.SubscriptionToken,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.TrialUsed,
		&i.ReferrerID,
		&i.ReferralCode,
		&i.IsBanned,
		&i.BanReason,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, password_hash, status, plan_id, traffic_limit, traffic_used, expires_at, subscription_token, note, created_at, updated_at, telegram_id, telegram_username, trial_used, referrer_id, referral_code, is_banned, ban_reason FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Status,
		&i.PlanID,
		&i.TrafficLimit,
		&i.TrafficUsed,
		&i.ExpiresAt,
		&i.SubscriptionToken,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.TrialUsed,
		&i.ReferrerID,
		&i.ReferralCode,
		&i.IsBanned,
		&i.BanReason,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, username, password_hash, status, plan_id, traffic_limit, traffic_used, expires_at, subscription_token, note, created_at, updated_at, telegram_id, telegram_username, trial_used, referrer_id, referral_code, is_banned, ban_reason FROM users
WHERE ($1 = '' OR status = $1)
AND ($2::uuid IS NULL OR $2::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR plan_id = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListUsersParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 uuid.UUID   `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.Status,
			&i.PlanID,
			&i.TrafficLimit,
			&i.TrafficUsed,
			&i.ExpiresAt,
			&i.SubscriptionToken,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TelegramID,
			&i.TelegramUsername,
			&i.TrialUsed,
			&i.ReferrerID,
			&i.ReferralCode,
			&i.IsBanned,
			&i.BanReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetUserTraffic = `-- name: ResetUserTraffic :exec
UPDATE users SET traffic_used = 0, updated_at = now() WHERE id = $1
`

func (q *Queries) ResetUserTraffic(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetUserTraffic, id)
	return err
}

const rotateUserSubscriptionToken = `-- name: RotateUserSubscriptionToken :one
UPDATE users SET subscription_token = gen_random_uuid(), updated_at = now() WHERE id = $1 RETURNING id, email, username, password_hash, status, plan_id, traffic_limit, traffic_used, expires_at, subscription_token, note, created_at, updated_at, telegram_id, telegram_username, trial_used, referrer_id, referral_code, is_banned, ban_reason
`

func (q *Queries) RotateUserSubscriptionToken(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, rotateUserSubscriptionToken, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Status,
		&i.PlanID,
		&i.TrafficLimit,
		&i.TrafficUsed,
		&i.ExpiresAt,
		&i.SubscriptionToken,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.TrialUsed,
		&i.ReferrerID,
		&i.ReferralCode,
		&i.IsBanned,
		&i.BanReason,
	)
	return i, err
}

const setUserBanStatus = `-- name: SetUserBanStatus :exec
UPDATE users SET is_banned = $2, ban_reason = $3, updated_at = now() WHERE id = $1
`

type SetUserBanStatusParams struct {
	ID        uuid.UUID   `json:"id"`
	IsBanned  pgtype.Bool `json:"is_banned"`
	BanReason pgtype.Text `json:"ban_reason"`
}

func (q *Queries) SetUserBanStatus(ctx context.Context, arg SetUserBanStatusParams) error {
	_, err := q.db.Exec(ctx, setUserBanStatus, arg.ID, arg.IsBanned, arg.BanReason)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2, username = $3, password_hash = $4, status = $5, plan_id = $6, traffic_limit = $7, expires_at = $8, note = $9, updated_at = now()
WHERE id = $1
RETURNING id, email, username, password_hash, status, plan_id, traffic_limit, traffic_used, expires_at, subscription_token, note, created_at, updated_at, telegram_id, telegram_username, trial_used, referrer_id, referral_code, is_banned, ban_reason
`

type UpdateUserParams struct {
	ID           uuid.UUID          `json:"id"`
	Email        pgtype.Text        `json:"email"`
	Username     string             `json:"username"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	Status       pgtype.Text        `json:"status"`
	PlanID       pgtype.UUID        `json:"plan_id"`
	TrafficLimit pgtype.Int8        `json:"traffic_limit"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	Note         pgtype.Text        `json:"note"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.Status,
		arg.PlanID,
		arg.TrafficLimit,
		arg.ExpiresAt,
		arg.Note,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Status,
		&i.PlanID,
		&i.TrafficLimit,
		&i.TrafficUsed,
		&i.ExpiresAt,
		&i.SubscriptionToken,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.TrialUsed,
		&i.ReferrerID,
		&i.ReferralCode,
		&i.IsBanned,
		&i.BanReason,
	)
	return i, err
}

const updateUserTraffic = `-- name: UpdateUserTraffic :exec
UPDATE users SET traffic_used = traffic_used + $2, updated_at = now() WHERE id = $1
`

type UpdateUserTrafficParams struct {
	ID          uuid.UUID   `json:"id"`
	TrafficUsed pgtype.Int8 `json:"traffic_used"`
}

func (q *Queries) UpdateUserTraffic(ctx context.Context, arg UpdateUserTrafficParams) error {
	_, err := q.db.Exec(ctx, updateUserTraffic, arg.ID, arg.TrafficUsed)
	return err
}

const updateUserTelegram = `-- name: UpdateUserTelegram :one
UPDATE users
SET telegram_id = $2, telegram_username = $3, trial_used = $4, referrer_id = $5, referral_code = $6, updated_at = now()
WHERE id = $1
RETURNING id, email, username, password_hash, status, plan_id, traffic_limit, traffic_used, expires_at, subscription_token, note, created_at, updated_at, telegram_id, telegram_username, trial_used, referrer_id, referral_code, is_banned, ban_reason
`

type UpdateUserTelegramParams struct {
	ID               uuid.UUID   `json:"id"`
	TelegramID       pgtype.Int8 `json:"telegram_id"`
	TelegramUsername pgtype.Text `json:"telegram_username"`
	TrialUsed        pgtype.Bool `json:"trial_used"`
	ReferrerID       pgtype.UUID `json:"referrer_id"`
	ReferralCode     pgtype.Text `json:"referral_code"`
}

func (q *Queries) UpdateUserTelegram(ctx context.Context, arg UpdateUserTelegramParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserTelegram,
		arg.ID,
		arg.TelegramID,
		arg.TelegramUsername,
		arg.TrialUsed,
		arg.ReferrerID,
		arg.ReferralCode,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Status,
		&i.PlanID,
		&i.TrafficLimit,
		&i.TrafficUsed,
		&i.ExpiresAt,
		&i.SubscriptionToken,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.TrialUsed,
		&i.ReferrerID,
		&i.ReferralCode,
		&i.IsBanned,
		&i.BanReason,
	)
	return i, err
}

const countReferralsByUserID = `-- name: CountReferralsByUserID :one
SELECT COUNT(*) FROM users WHERE referrer_id = $1
`

func (q *Queries) CountReferralsByUserID(ctx context.Context, referrerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReferralsByUserID, referrerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listUsersForBroadcast = `-- name: ListUsersForBroadcast :many
SELECT telegram_id FROM users
WHERE telegram_id IS NOT NULL AND is_banned = false
AND (
    $1 = 'all'
    OR ($1 = 'active' AND status = 'active' AND expires_at > now())
    OR ($1 = 'expired' AND (status != 'active' OR expires_at <= now()))
)
`

func (q *Queries) ListUsersForBroadcast(ctx context.Context, segment string) ([]int64, error) {
	rows, err := q.db.Query(ctx, listUsersForBroadcast, segment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var tgID pgtype.Int8
		if err := rows.Scan(&tgID); err != nil {
			return nil, err
		}
		if tgID.Valid {
			items = append(items, tgID.Int64)
		}
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

