// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (url, secret, events, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, url, secret, events, is_active, created_at, updated_at
`

type CreateWebhookParams struct {
	Url      string      `json:"url"`
	Secret   string      `json:"secret"`
	Events   []string    `json:"events"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.Url,
		arg.Secret,
		arg.Events,
		arg.IsActive,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks WHERE id = $1
`

func (q *Queries) DeleteWebhook(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWebhook, id)
	return err
}

const getWebhookByID = `-- name: GetWebhookByID :one
SELECT id, url, secret, events, is_active, created_at, updated_at FROM webhooks WHERE id = $1
`

func (q *Queries) GetWebhookByID(ctx context.Context, id uuid.UUID) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhookByID, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveWebhooks = `-- name: ListActiveWebhooks :many
SELECT id, url, secret, events, is_active, created_at, updated_at FROM webhooks WHERE is_active = true ORDER BY created_at DESC
`

func (q *Queries) ListActiveWebhooks(ctx context.Context) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listActiveWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, url, secret, events, is_active, created_at, updated_at FROM webhooks ORDER BY created_at DESC
`

func (q *Queries) ListWebhooks(ctx context.Context) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE webhooks
SET url = $2, secret = $3, events = $4, is_active = $5, updated_at = now()
WHERE id = $1
RETURNING id, url, secret, events, is_active, created_at, updated_at
`

type UpdateWebhookParams struct {
	ID       uuid.UUID   `json:"id"`
	Url      string      `json:"url"`
	Secret   string      `json:"secret"`
	Events   []string    `json:"events"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, updateWebhook,
		arg.ID,
		arg.Url,
		arg.Secret,
		arg.Events,
		arg.IsActive,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
