// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeStatus int32

const (
	NodeStatus_NODE_STATUS_UNSPECIFIED NodeStatus = 0
	NodeStatus_NODE_STATUS_ONLINE      NodeStatus = 1
	NodeStatus_NODE_STATUS_DEGRADED    NodeStatus = 2
	NodeStatus_NODE_STATUS_DRAINING    NodeStatus = 3
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_STATUS_UNSPECIFIED",
		1: "NODE_STATUS_ONLINE",
		2: "NODE_STATUS_DEGRADED",
		3: "NODE_STATUS_DRAINING",
	}
	NodeStatus_value = map[string]int32{
		"NODE_STATUS_UNSPECIFIED": 0,
		"NODE_STATUS_ONLINE":      1,
		"NODE_STATUS_DEGRADED":    2,
		"NODE_STATUS_DRAINING":    3,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_agent_v1_agent_proto_enumTypes[0]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_Metrics
	//	*AgentMessage_Log
	//	*AgentMessage_ConfigAck
	//	*AgentMessage_CommandResult
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetMetrics() *MetricsReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *AgentMessage) GetLog() *LogEntry {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *AgentMessage) GetConfigAck() *ConfigAck {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ConfigAck); ok {
			return x.ConfigAck
		}
	}
	return nil
}

func (x *AgentMessage) GetCommandResult() *CommandResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_CommandResult); ok {
			return x.CommandResult
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_Metrics struct {
	Metrics *MetricsReport `protobuf:"bytes,3,opt,name=metrics,proto3,oneof"`
}

type AgentMessage_Log struct {
	Log *LogEntry `protobuf:"bytes,4,opt,name=log,proto3,oneof"`
}

type AgentMessage_ConfigAck struct {
	ConfigAck *ConfigAck `protobuf:"bytes,5,opt,name=config_ack,json=configAck,proto3,oneof"`
}

type AgentMessage_CommandResult struct {
	CommandResult *CommandResult `protobuf:"bytes,6,opt,name=command_result,json=commandResult,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_Metrics) isAgentMessage_Payload() {}

func (*AgentMessage_Log) isAgentMessage_Payload() {}

func (*AgentMessage_ConfigAck) isAgentMessage_Payload() {}

func (*AgentMessage_CommandResult) isAgentMessage_Payload() {}

type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlMessage_Config
	//	*ControlMessage_Command
	//	*ControlMessage_Ping
	Payload       isControlMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ControlMessage) GetPayload() isControlMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlMessage) GetConfig() *ConfigUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *ControlMessage) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ControlMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isControlMessage_Payload interface {
	isControlMessage_Payload()
}

type ControlMessage_Config struct {
	Config *ConfigUpdate `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type ControlMessage_Command struct {
	Command *Command `protobuf:"bytes,2,opt,name=command,proto3,oneof"`
}

type ControlMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

func (*ControlMessage_Config) isControlMessage_Payload() {}

func (*ControlMessage_Command) isControlMessage_Payload() {}

func (*ControlMessage_Ping) isControlMessage_Payload() {}

// Agent -> CP: Initial registration
type RegisterRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NodeName           string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	WireguardPublicKey string                 `protobuf:"bytes,2,opt,name=wireguard_public_key,json=wireguardPublicKey,proto3" json:"wireguard_public_key,omitempty"`
	Version            string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Labels             map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Architecture       string                 `protobuf:"bytes,5,opt,name=architecture,proto3" json:"architecture,omitempty"`
	KernelVersion      string                 `protobuf:"bytes,6,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *RegisterRequest) GetWireguardPublicKey() string {
	if x != nil {
		return x.WireguardPublicKey
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterRequest) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *RegisterRequest) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

// Agent -> CP: Periodic heartbeat (every 10s)
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        NodeStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=vpnbuilder.agent.v1.NodeStatus" json:"status,omitempty"`
	System        *SystemInfo            `protobuf:"bytes,3,opt,name=system,proto3" json:"system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Heartbeat) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

func (x *Heartbeat) GetSystem() *SystemInfo {
	if x != nil {
		return x.System
	}
	return nil
}

type SystemInfo struct {
	state           protoimpl.MessageState       `protogen:"open.v1"`
	UptimeSeconds   int64                        `protobuf:"varint,1,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	CpuUsagePercent float64                      `protobuf:"fixed64,2,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryTotal     uint64                       `protobuf:"varint,3,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	MemoryUsed      uint64                       `protobuf:"varint,4,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	DiskTotal       uint64                       `protobuf:"varint,5,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"`
	DiskUsed        uint64                       `protobuf:"varint,6,opt,name=disk_used,json=diskUsed,proto3" json:"disk_used,omitempty"`
	Networks        map[string]*NetworkInterface `protobuf:"bytes,7,rep,name=networks,proto3" json:"networks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *SystemInfo) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *SystemInfo) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *SystemInfo) GetMemoryTotal() uint64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *SystemInfo) GetMemoryUsed() uint64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *SystemInfo) GetDiskTotal() uint64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

func (x *SystemInfo) GetDiskUsed() uint64 {
	if x != nil {
		return x.DiskUsed
	}
	return 0
}

func (x *SystemInfo) GetNetworks() map[string]*NetworkInterface {
	if x != nil {
		return x.Networks
	}
	return nil
}

type NetworkInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ips           []string               `protobuf:"bytes,2,rep,name=ips,proto3" json:"ips,omitempty"`
	RxBytes       uint64                 `protobuf:"varint,3,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes       uint64                 `protobuf:"varint,4,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterface) Reset() {
	*x = NetworkInterface{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterface) ProtoMessage() {}

func (x *NetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterface.ProtoReflect.Descriptor instead.
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInterface) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *NetworkInterface) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *NetworkInterface) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

// Agent -> CP: Traffic metrics (every 30s)
type MetricsReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Protocols     []*ProtocolMetrics     `protobuf:"bytes,2,rep,name=protocols,proto3" json:"protocols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsReport) Reset() {
	*x = MetricsReport{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsReport) ProtoMessage() {}

func (x *MetricsReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsReport.ProtoReflect.Descriptor instead.
func (*MetricsReport) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *MetricsReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricsReport) GetProtocols() []*ProtocolMetrics {
	if x != nil {
		return x.Protocols
	}
	return nil
}

type ProtocolMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Peers         []*PeerMetric          `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolMetrics) Reset() {
	*x = ProtocolMetrics{}
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolMetrics) ProtoMessage() {}

func (x *ProtocolMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolMetrics.ProtoReflect.Descriptor instead.
func (*ProtocolMetrics) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ProtocolMetrics) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ProtocolMetrics) GetPeers() []*PeerMetric {
	if x != nil {
		return x.Peers
	}
	return nil
}

type PeerMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	RxBytes       int64                  `protobuf:"varint,2,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes       int64                  `protobuf:"varint,3,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	LastHandshake int64                  `protobuf:"varint,4,opt,name=last_handshake,json=lastHandshake,proto3" json:"last_handshake,omitempty"`
	Endpoint      string                 `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	IsOnline      bool                   `protobuf:"varint,6,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerMetric) Reset() {
	*x = PeerMetric{}
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMetric) ProtoMessage() {}

func (x *PeerMetric) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerMetric.ProtoReflect.Descriptor instead.
func (*PeerMetric) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *PeerMetric) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerMetric) GetRxBytes() int64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *PeerMetric) GetTxBytes() int64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *PeerMetric) GetLastHandshake() int64 {
	if x != nil {
		return x.LastHandshake
	}
	return 0
}

func (x *PeerMetric) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PeerMetric) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

// Agent -> CP: Log entries (optional, for debugging)
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Agent -> CP: Acknowledgment of config application
type ConfigAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion int64                  `protobuf:"varint,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigAck) Reset() {
	*x = ConfigAck{}
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigAck) ProtoMessage() {}

func (x *ConfigAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigAck.ProtoReflect.Descriptor instead.
func (*ConfigAck) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigAck) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *ConfigAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Agent -> CP: Command execution result
type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CommandResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

// CP -> Agent: Configuration update (full or delta)
type ConfigUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion int64                  `protobuf:"varint,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	IsFull        bool                   `protobuf:"varint,2,opt,name=is_full,json=isFull,proto3" json:"is_full,omitempty"`
	Users         []*NodeUserConfig      `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	NodeConfig    *NodeConfig            `protobuf:"bytes,4,opt,name=node_config,json=nodeConfig,proto3" json:"node_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ConfigUpdate) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *ConfigUpdate) GetIsFull() bool {
	if x != nil {
		return x.IsFull
	}
	return false
}

func (x *ConfigUpdate) GetUsers() []*NodeUserConfig {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ConfigUpdate) GetNodeConfig() *NodeConfig {
	if x != nil {
		return x.NodeConfig
	}
	return nil
}

type NodeConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WireguardInterface string                 `protobuf:"bytes,1,opt,name=wireguard_interface,json=wireguardInterface,proto3" json:"wireguard_interface,omitempty"`
	WireguardSubnetV4  string                 `protobuf:"bytes,2,opt,name=wireguard_subnet_v4,json=wireguardSubnetV4,proto3" json:"wireguard_subnet_v4,omitempty"`
	WireguardSubnetV6  string                 `protobuf:"bytes,3,opt,name=wireguard_subnet_v6,json=wireguardSubnetV6,proto3" json:"wireguard_subnet_v6,omitempty"`
	WireguardMtu       int32                  `protobuf:"varint,4,opt,name=wireguard_mtu,json=wireguardMtu,proto3" json:"wireguard_mtu,omitempty"`
	WireguardKeepalive int32                  `protobuf:"varint,5,opt,name=wireguard_keepalive,json=wireguardKeepalive,proto3" json:"wireguard_keepalive,omitempty"`
	DnsServers         map[string]string      `protobuf:"bytes,6,rep,name=dns_servers,json=dnsServers,proto3" json:"dns_servers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Xray               *XrayConfig            `protobuf:"bytes,7,opt,name=xray,proto3" json:"xray,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NodeConfig) Reset() {
	*x = NodeConfig{}
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfig) ProtoMessage() {}

func (x *NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfig.ProtoReflect.Descriptor instead.
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *NodeConfig) GetWireguardInterface() string {
	if x != nil {
		return x.WireguardInterface
	}
	return ""
}

func (x *NodeConfig) GetWireguardSubnetV4() string {
	if x != nil {
		return x.WireguardSubnetV4
	}
	return ""
}

func (x *NodeConfig) GetWireguardSubnetV6() string {
	if x != nil {
		return x.WireguardSubnetV6
	}
	return ""
}

func (x *NodeConfig) GetWireguardMtu() int32 {
	if x != nil {
		return x.WireguardMtu
	}
	return 0
}

func (x *NodeConfig) GetWireguardKeepalive() int32 {
	if x != nil {
		return x.WireguardKeepalive
	}
	return 0
}

func (x *NodeConfig) GetDnsServers() map[string]string {
	if x != nil {
		return x.DnsServers
	}
	return nil
}

func (x *NodeConfig) GetXray() *XrayConfig {
	if x != nil {
		return x.Xray
	}
	return nil
}

type XrayConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	LogLevel      string                 `protobuf:"bytes,2,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	Inbounds      []*InboundConfig       `protobuf:"bytes,3,rep,name=inbounds,proto3" json:"inbounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XrayConfig) Reset() {
	*x = XrayConfig{}
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XrayConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XrayConfig) ProtoMessage() {}

func (x *XrayConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XrayConfig.ProtoReflect.Descriptor instead.
func (*XrayConfig) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *XrayConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *XrayConfig) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *XrayConfig) GetInbounds() []*InboundConfig {
	if x != nil {
		return x.Inbounds
	}
	return nil
}

type InboundConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Tag            string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Protocol       string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"` // vless, vmess, trojan, shadowsocks
	Listen         string                 `protobuf:"bytes,3,opt,name=listen,proto3" json:"listen,omitempty"`
	Port           int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Network        string                 `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`   // tcp, ws, grpc, httpupgrade
	Security       string                 `protobuf:"bytes,6,opt,name=security,proto3" json:"security,omitempty"` // none, tls, reality
	Settings       map[string]string      `protobuf:"bytes,7,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StreamSettings map[string]string      `protobuf:"bytes,8,rep,name=stream_settings,json=streamSettings,proto3" json:"stream_settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sniffing       map[string]string      `protobuf:"bytes,9,rep,name=sniffing,proto3" json:"sniffing,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InboundConfig) Reset() {
	*x = InboundConfig{}
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundConfig) ProtoMessage() {}

func (x *InboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundConfig.ProtoReflect.Descriptor instead.
func (*InboundConfig) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *InboundConfig) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *InboundConfig) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *InboundConfig) GetListen() string {
	if x != nil {
		return x.Listen
	}
	return ""
}

func (x *InboundConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *InboundConfig) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *InboundConfig) GetSecurity() string {
	if x != nil {
		return x.Security
	}
	return ""
}

func (x *InboundConfig) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *InboundConfig) GetStreamSettings() map[string]string {
	if x != nil {
		return x.StreamSettings
	}
	return nil
}

func (x *InboundConfig) GetSniffing() map[string]string {
	if x != nil {
		return x.Sniffing
	}
	return nil
}

type NodeUserConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Credentials   []*CredentialConfig    `protobuf:"bytes,2,rep,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeUserConfig) Reset() {
	*x = NodeUserConfig{}
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeUserConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeUserConfig) ProtoMessage() {}

func (x *NodeUserConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeUserConfig.ProtoReflect.Descriptor instead.
func (*NodeUserConfig) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *NodeUserConfig) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NodeUserConfig) GetCredentials() []*CredentialConfig {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type CredentialConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CredentialId  string                 `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ConfigBytes   []byte                 `protobuf:"bytes,3,opt,name=config_bytes,json=configBytes,proto3" json:"config_bytes,omitempty"` // Protocol-specific serialized config
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialConfig) Reset() {
	*x = CredentialConfig{}
	mi := &file_agent_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialConfig) ProtoMessage() {}

func (x *CredentialConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialConfig.ProtoReflect.Descriptor instead.
func (*CredentialConfig) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *CredentialConfig) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *CredentialConfig) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *CredentialConfig) GetConfigBytes() []byte {
	if x != nil {
		return x.ConfigBytes
	}
	return nil
}

// CP -> Agent: Command to execute
type Command struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommandId      string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // restart_protocol, reload_config, reboot, rotate_certs
	Params         map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int64                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_agent_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Command) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Command) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// CP -> Agent: Keepalive ping
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_agent_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{19}
}

func (x *Ping) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\x13vpnbuilder.agent.v1\"\x9e\x03\n" +
	"\fAgentMessage\x12B\n" +
	"\bregister\x18\x01 \x01(\v2$.vpnbuilder.agent.v1.RegisterRequestH\x00R\bregister\x12>\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1e.vpnbuilder.agent.v1.HeartbeatH\x00R\theartbeat\x12>\n" +
	"\ametrics\x18\x03 \x01(\v2\".vpnbuilder.agent.v1.MetricsReportH\x00R\ametrics\x121\n" +
	"\x03log\x18\x04 \x01(\v2\x1d.vpnbuilder.agent.v1.LogEntryH\x00R\x03log\x12?\n" +
	"\n" +
	"config_ack\x18\x05 \x01(\v2\x1e.vpnbuilder.agent.v1.ConfigAckH\x00R\tconfigAck\x12K\n" +
	"\x0ecommand_result\x18\x06 \x01(\v2\".vpnbuilder.agent.v1.CommandResultH\x00R\rcommandResultB\t\n" +
	"\apayload\"\xc3\x01\n" +
	"\x0eControlMessage\x12;\n" +
	"\x06config\x18\x01 \x01(\v2!.vpnbuilder.agent.v1.ConfigUpdateH\x00R\x06config\x128\n" +
	"\acommand\x18\x02 \x01(\v2\x1c.vpnbuilder.agent.v1.CommandH\x00R\acommand\x12/\n" +
	"\x04ping\x18\x03 \x01(\v2\x19.vpnbuilder.agent.v1.PingH\x00R\x04pingB\t\n" +
	"\apayload\"\xca\x02\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x120\n" +
	"\x14wireguard_public_key\x18\x02 \x01(\tR\x12wireguardPublicKey\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12H\n" +
	"\x06labels\x18\x04 \x03(\v20.vpnbuilder.agent.v1.RegisterRequest.LabelsEntryR\x06labels\x12\"\n" +
	"\farchitecture\x18\x05 \x01(\tR\farchitecture\x12%\n" +
	"\x0ekernel_version\x18\x06 \x01(\tR\rkernelVersion\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x01\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.vpnbuilder.agent.v1.NodeStatusR\x06status\x127\n" +
	"\x06system\x18\x03 \x01(\v2\x1f.vpnbuilder.agent.v1.SystemInfoR\x06system\"\x8e\x03\n" +
	"\n" +
	"SystemInfo\x12%\n" +
	"\x0euptime_seconds\x18\x01 \x01(\x03R\ruptimeSeconds\x12*\n" +
	"\x11cpu_usage_percent\x18\x02 \x01(\x01R\x0fcpuUsagePercent\x12!\n" +
	"\fmemory_total\x18\x03 \x01(\x04R\vmemoryTotal\x12\x1f\n" +
	"\vmemory_used\x18\x04 \x01(\x04R\n" +
	"memoryUsed\x12\x1d\n" +
	"\n" +
	"disk_total\x18\x05 \x01(\x04R\tdiskTotal\x12\x1b\n" +
	"\tdisk_used\x18\x06 \x01(\x04R\bdiskUsed\x12I\n" +
	"\bnetworks\x18\a \x03(\v2-.vpnbuilder.agent.v1.SystemInfo.NetworksEntryR\bnetworks\x1ab\n" +
	"\rNetworksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12;\n" +
	"\x05value\x18\x02 \x01(\v2%.vpnbuilder.agent.v1.NetworkInterfaceR\x05value:\x028\x01\"n\n" +
	"\x10NetworkInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03ips\x18\x02 \x03(\tR\x03ips\x12\x19\n" +
	"\brx_bytes\x18\x03 \x01(\x04R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x04 \x01(\x04R\atxBytes\"q\n" +
	"\rMetricsReport\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12B\n" +
	"\tprotocols\x18\x02 \x03(\v2$.vpnbuilder.agent.v1.ProtocolMetricsR\tprotocols\"d\n" +
	"\x0fProtocolMetrics\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x125\n" +
	"\x05peers\x18\x02 \x03(\v2\x1f.vpnbuilder.agent.v1.PeerMetricR\x05peers\"\xbb\x01\n" +
	"\n" +
	"PeerMetric\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x19\n" +
	"\brx_bytes\x18\x02 \x01(\x03R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x03 \x01(\x03R\atxBytes\x12%\n" +
	"\x0elast_handshake\x18\x04 \x01(\x03R\rlastHandshake\x12\x1a\n" +
	"\bendpoint\x18\x05 \x01(\tR\bendpoint\x12\x1b\n" +
	"\tis_online\x18\x06 \x01(\bR\bisOnline\"\xd6\x01\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12A\n" +
	"\x06fields\x18\x04 \x03(\v2).vpnbuilder.agent.v1.LogEntry.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"b\n" +
	"\tConfigAck\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\x03R\rconfigVersion\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"}\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\"\xcb\x01\n" +
	"\fConfigUpdate\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\x03R\rconfigVersion\x12\x17\n" +
	"\ais_full\x18\x02 \x01(\bR\x06isFull\x129\n" +
	"\x05users\x18\x03 \x03(\v2#.vpnbuilder.agent.v1.NodeUserConfigR\x05users\x12@\n" +
	"\vnode_config\x18\x04 \x01(\v2\x1f.vpnbuilder.agent.v1.NodeConfigR\n" +
	"nodeConfig\"\xb9\x03\n" +
	"\n" +
	"NodeConfig\x12/\n" +
	"\x13wireguard_interface\x18\x01 \x01(\tR\x12wireguardInterface\x12.\n" +
	"\x13wireguard_subnet_v4\x18\x02 \x01(\tR\x11wireguardSubnetV4\x12.\n" +
	"\x13wireguard_subnet_v6\x18\x03 \x01(\tR\x11wireguardSubnetV6\x12#\n" +
	"\rwireguard_mtu\x18\x04 \x01(\x05R\fwireguardMtu\x12/\n" +
	"\x13wireguard_keepalive\x18\x05 \x01(\x05R\x12wireguardKeepalive\x12P\n" +
	"\vdns_servers\x18\x06 \x03(\v2/.vpnbuilder.agent.v1.NodeConfig.DnsServersEntryR\n" +
	"dnsServers\x123\n" +
	"\x04xray\x18\a \x01(\v2\x1f.vpnbuilder.agent.v1.XrayConfigR\x04xray\x1a=\n" +
	"\x0fDnsServersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x01\n" +
	"\n" +
	"XrayConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1b\n" +
	"\tlog_level\x18\x02 \x01(\tR\blogLevel\x12>\n" +
	"\binbounds\x18\x03 \x03(\v2\".vpnbuilder.agent.v1.InboundConfigR\binbounds\"\xd9\x04\n" +
	"\rInboundConfig\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06listen\x18\x03 \x01(\tR\x06listen\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x18\n" +
	"\anetwork\x18\x05 \x01(\tR\anetwork\x12\x1a\n" +
	"\bsecurity\x18\x06 \x01(\tR\bsecurity\x12L\n" +
	"\bsettings\x18\a \x03(\v20.vpnbuilder.agent.v1.InboundConfig.SettingsEntryR\bsettings\x12_\n" +
	"\x0fstream_settings\x18\b \x03(\v26.vpnbuilder.agent.v1.InboundConfig.StreamSettingsEntryR\x0estreamSettings\x12L\n" +
	"\bsniffing\x18\t \x03(\v20.vpnbuilder.agent.v1.InboundConfig.SniffingEntryR\bsniffing\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13StreamSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rSniffingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\x0eNodeUserConfig\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12G\n" +
	"\vcredentials\x18\x02 \x03(\v2%.vpnbuilder.agent.v1.CredentialConfigR\vcredentials\"v\n" +
	"\x10CredentialConfig\x12#\n" +
	"\rcredential_id\x18\x01 \x01(\tR\fcredentialId\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12!\n" +
	"\fconfig_bytes\x18\x03 \x01(\fR\vconfigBytes\"\xe2\x01\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12@\n" +
	"\x06params\x18\x03 \x03(\v2(.vpnbuilder.agent.v1.Command.ParamsEntryR\x06params\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x03R\x0etimeoutSeconds\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"$\n" +
	"\x04Ping\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp*u\n" +
	"\n" +
	"NodeStatus\x12\x1b\n" +
	"\x17NODE_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12NODE_STATUS_ONLINE\x10\x01\x12\x18\n" +
	"\x14NODE_STATUS_DEGRADED\x10\x02\x12\x18\n" +
	"\x14NODE_STATUS_DRAINING\x10\x032e\n" +
	"\fAgentService\x12U\n" +
	"\aConnect\x12!.vpnbuilder.agent.v1.AgentMessage\x1a#.vpnbuilder.agent.v1.ControlMessage(\x010\x01BHZFgithub.com/ivanchik-byte/Simple-VPN-Builder/pkg/proto/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_agent_v1_agent_proto_goTypes = []any{
	(NodeStatus)(0),          // 0: vpnbuilder.agent.v1.NodeStatus
	(*AgentMessage)(nil),     // 1: vpnbuilder.agent.v1.AgentMessage
	(*ControlMessage)(nil),   // 2: vpnbuilder.agent.v1.ControlMessage
	(*RegisterRequest)(nil),  // 3: vpnbuilder.agent.v1.RegisterRequest
	(*Heartbeat)(nil),        // 4: vpnbuilder.agent.v1.Heartbeat
	(*SystemInfo)(nil),       // 5: vpnbuilder.agent.v1.SystemInfo
	(*NetworkInterface)(nil), // 6: vpnbuilder.agent.v1.NetworkInterface
	(*MetricsReport)(nil),    // 7: vpnbuilder.agent.v1.MetricsReport
	(*ProtocolMetrics)(nil),  // 8: vpnbuilder.agent.v1.ProtocolMetrics
	(*PeerMetric)(nil),       // 9: vpnbuilder.agent.v1.PeerMetric
	(*LogEntry)(nil),         // 10: vpnbuilder.agent.v1.LogEntry
	(*ConfigAck)(nil),        // 11: vpnbuilder.agent.v1.ConfigAck
	(*CommandResult)(nil),    // 12: vpnbuilder.agent.v1.CommandResult
	(*ConfigUpdate)(nil),     // 13: vpnbuilder.agent.v1.ConfigUpdate
	(*NodeConfig)(nil),       // 14: vpnbuilder.agent.v1.NodeConfig
	(*XrayConfig)(nil),       // 15: vpnbuilder.agent.v1.XrayConfig
	(*InboundConfig)(nil),    // 16: vpnbuilder.agent.v1.InboundConfig
	(*NodeUserConfig)(nil),   // 17: vpnbuilder.agent.v1.NodeUserConfig
	(*CredentialConfig)(nil), // 18: vpnbuilder.agent.v1.CredentialConfig
	(*Command)(nil),          // 19: vpnbuilder.agent.v1.Command
	(*Ping)(nil),             // 20: vpnbuilder.agent.v1.Ping
	nil,                      // 21: vpnbuilder.agent.v1.RegisterRequest.LabelsEntry
	nil,                      // 22: vpnbuilder.agent.v1.SystemInfo.NetworksEntry
	nil,                      // 23: vpnbuilder.agent.v1.LogEntry.FieldsEntry
	nil,                      // 24: vpnbuilder.agent.v1.NodeConfig.DnsServersEntry
	nil,                      // 25: vpnbuilder.agent.v1.InboundConfig.SettingsEntry
	nil,                      // 26: vpnbuilder.agent.v1.InboundConfig.StreamSettingsEntry
	nil,                      // 27: vpnbuilder.agent.v1.InboundConfig.SniffingEntry
	nil,                      // 28: vpnbuilder.agent.v1.Command.ParamsEntry
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	3,  // 0: vpnbuilder.agent.v1.AgentMessage.register:type_name -> vpnbuilder.agent.v1.RegisterRequest
	4,  // 1: vpnbuilder.agent.v1.AgentMessage.heartbeat:type_name -> vpnbuilder.agent.v1.Heartbeat
	7,  // 2: vpnbuilder.agent.v1.AgentMessage.metrics:type_name -> vpnbuilder.agent.v1.MetricsReport
	10, // 3: vpnbuilder.agent.v1.AgentMessage.log:type_name -> vpnbuilder.agent.v1.LogEntry
	11, // 4: vpnbuilder.agent.v1.AgentMessage.config_ack:type_name -> vpnbuilder.agent.v1.ConfigAck
	12, // 5: vpnbuilder.agent.v1.AgentMessage.command_result:type_name -> vpnbuilder.agent.v1.CommandResult
	13, // 6: vpnbuilder.agent.v1.ControlMessage.config:type_name -> vpnbuilder.agent.v1.ConfigUpdate
	19, // 7: vpnbuilder.agent.v1.ControlMessage.command:type_name -> vpnbuilder.agent.v1.Command
	20, // 8: vpnbuilder.agent.v1.ControlMessage.ping:type_name -> vpnbuilder.agent.v1.Ping
	21, // 9: vpnbuilder.agent.v1.RegisterRequest.labels:type_name -> vpnbuilder.agent.v1.RegisterRequest.LabelsEntry
	0,  // 10: vpnbuilder.agent.v1.Heartbeat.status:type_name -> vpnbuilder.agent.v1.NodeStatus
	5,  // 11: vpnbuilder.agent.v1.Heartbeat.system:type_name -> vpnbuilder.agent.v1.SystemInfo
	22, // 12: vpnbuilder.agent.v1.SystemInfo.networks:type_name -> vpnbuilder.agent.v1.SystemInfo.NetworksEntry
	8,  // 13: vpnbuilder.agent.v1.MetricsReport.protocols:type_name -> vpnbuilder.agent.v1.ProtocolMetrics
	9,  // 14: vpnbuilder.agent.v1.ProtocolMetrics.peers:type_name -> vpnbuilder.agent.v1.PeerMetric
	23, // 15: vpnbuilder.agent.v1.LogEntry.fields:type_name -> vpnbuilder.agent.v1.LogEntry.FieldsEntry
	17, // 16: vpnbuilder.agent.v1.ConfigUpdate.users:type_name -> vpnbuilder.agent.v1.NodeUserConfig
	14, // 17: vpnbuilder.agent.v1.ConfigUpdate.node_config:type_name -> vpnbuilder.agent.v1.NodeConfig
	24, // 18: vpnbuilder.agent.v1.NodeConfig.dns_servers:type_name -> vpnbuilder.agent.v1.NodeConfig.DnsServersEntry
	15, // 19: vpnbuilder.agent.v1.NodeConfig.xray:type_name -> vpnbuilder.agent.v1.XrayConfig
	16, // 20: vpnbuilder.agent.v1.XrayConfig.inbounds:type_name -> vpnbuilder.agent.v1.InboundConfig
	25, // 21: vpnbuilder.agent.v1.InboundConfig.settings:type_name -> vpnbuilder.agent.v1.InboundConfig.SettingsEntry
	26, // 22: vpnbuilder.agent.v1.InboundConfig.stream_settings:type_name -> vpnbuilder.agent.v1.InboundConfig.StreamSettingsEntry
	27, // 23: vpnbuilder.agent.v1.InboundConfig.sniffing:type_name -> vpnbuilder.agent.v1.InboundConfig.SniffingEntry
	18, // 24: vpnbuilder.agent.v1.NodeUserConfig.credentials:type_name -> vpnbuilder.agent.v1.CredentialConfig
	28, // 25: vpnbuilder.agent.v1.Command.params:type_name -> vpnbuilder.agent.v1.Command.ParamsEntry
	6,  // 26: vpnbuilder.agent.v1.SystemInfo.NetworksEntry.value:type_name -> vpnbuilder.agent.v1.NetworkInterface
	1,  // 27: vpnbuilder.agent.v1.AgentService.Connect:input_type -> vpnbuilder.agent.v1.AgentMessage
	2,  // 28: vpnbuilder.agent.v1.AgentService.Connect:output_type -> vpnbuilder.agent.v1.ControlMessage
	28, // [28:29] is the sub-list for method output_type
	27, // [27:28] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	file_agent_v1_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_Metrics)(nil),
		(*AgentMessage_Log)(nil),
		(*AgentMessage_ConfigAck)(nil),
		(*AgentMessage_CommandResult)(nil),
	}
	file_agent_v1_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*ControlMessage_Config)(nil),
		(*ControlMessage_Command)(nil),
		(*ControlMessage_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
